<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>task_table_Upinfo</name>
   <tag></tag>
   <elementGuidId>8a8621fe-2457-4dd2-af1a-c22b2ab1eea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:dtFcltUpdateAddInfo:tb&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:dtFcltUpdateAddInfo:tb&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
