<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add Address.panelColumns t_1</name>
   <tag></tag>
   <elementGuidId>c227a7b8-9d59-42ca-a7b9-0d940523e398</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:contentWrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contentWrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Add Address
	
	
.panelColumns td {
	vertical-align: top;
}
//&lt;![CDATA[
		closeModal=function(){A4J.AJAX.Submit('frmMain',null,{'similarityGroupingId':'frmMain:j_id10','parameters':{'ajaxSingle':'frmMain:j_id10','frmMain:j_id10':'frmMain:j_id10'} ,'eventsQueue':'mQueueP'} )};
		//]]>WARNING







Richfaces.componentControl.attachAvailable('#frmMain\\:modalMessage_','onmaskclick','#frmMain\\:modalMessage_','hide')new ModalPanel('frmMain:modalMessage_',
				{
					width: 500,
					height: -1,

					minWidth: -1,
					minHeight: -1,

					resizeable: false,
					moveable: false,

					left: &quot;auto&quot;,
					top: &quot;auto&quot;,

					zindex: 1000,onresize: '',onmove: '',onshow: '',onhide: '',onbeforeshow: '',onbeforehide: '',
					domElementAttachment: &quot;&quot;,				
					keepVisualState: false,
					showWhenRendered: false,
					selectBehavior: &quot;disable&quot;,

					autosized: true,
					overlapEmbedObjects: false});

    

        if (document.title == &quot;&quot;) {
            document.title = &quot;:: MBF IT Core System 1.2.21 ::&quot;;
        } else {
            document.title = &quot;:: MBF IT Core System - Add Address 1.2.21 ::&quot;;
        }

    
        
            Address



Type
	ID Address




Address




Country
	AUS - Australia
	BEL - Belgium
	CAN - Canada
	CHN - China
	GBR - United Kingdom
	GER - Germany 
	HKG - Hongkong
	IDN - Indonesia
	JPN - Japan
	KOR - Korea, Republic of (South)
	MYS - Malaysia
	SGP - Singapore
	THA - Thailand
	USA - United States




Region/City
ACEH BARATACEH BARAT DAYAACEH BESARACEH JAYAACEH SELATANACEH SINGKILACEH TAMIANGACEH TENGAHACEH TENGGARAACEH TIMURACEH UTARAAGAMALORASAHANASMATBADUNGBALANGANBANDAR LAMPUNGBANDUNGBANDUNG BARATBANGGAIBANGGAI KEPULAUANBANGKABANGKA BARATBANGKA SELATANBANGKA TENGAHBANGKALANBANGLIBANJARBANJARNEGARABANTAENGBANTULBANYUASINBANYUMASBANYUWANGIBARITO KUALABARITO SELATANBARITO TIMURBARITO UTARABARRUBARRUBARUBATANGBATANG HARIBATU BARABEKASIBELITUNGBELITUNG TIMURBELUBENER MERIAHBENGKALISBENGKAYANGBENGKULUBENGKULU SELATANBENGKULU TENGAHBENGKULU UTARABERAUBIAK NUMFORBIMABIREUENBLITARBLORABOALEMOBOGORBOGORBOJONEGOROBOLAANG MONGONDOBOLAANG MONGONDO SELATANBOLAANG MONGONDO TIMURBOLMONG UTARABOMBANABONDOWOSOBONEBONE BOLANGOBOVEN DIGULBOYOLALIBREBESBULELENGBULUKUMBABULUNGANBUNGOBUOLBURUBURU SELATANBUTONBUTON UTARACIAMISCIANJURCILACAPCIREBONDAIRIDEIYAIDELI SERDANGDEMAKDHARMASRAYADOMPUDONGGALADONOROJOEMPAT LAWANGENDEENREKANGFAKFAKFLORES TIMURGARUTGAYO LUESGIANYARGORONTALOGORONTALO UTARAGOWAGRESIKGROBOGANGUNUNG KIDULGUNUNG MASHALMAHERA BARATHALMAHERA SELATANHALMAHERA TENGAHHALMAHERA TIMURHALMAHERA UTARAHULU SUNGAI SELATANHULU SUNGAI TENGAHHULU SUNGAI UTARAHUMBANG HASUNDUTANINDRAGIRI HILIRINDRAGIRI HULUINDRAMAYUINTAN JAYAJAKARTAJAKARTA BARATJAKARTA PUSATJAKARTA SELATANJAKARTA TIMURJAKARTA UTARAJAYAPURAJAYAWIJAYAJEMBERJEMBRANAJENEPONTOJEPARAJOMBANGKAB. TUALKABUPATEN DOGIYAIKABUPATEN DUGAKABUPATEN KLATENKABUPATEN LANNY JAYAKABUPATEN MABERAMO TENGAHKABUPATEN MALANGKABUPATEN MOJOKERTOKABUPATEN PUNCAKKABUPATEN YALIMOKAIMANAKAMPARKAPUASKAPUAS HULUKARANG ASEMKARANGANYARKARAWANGKARIMUNKAROKATINGANKAURKAYONG UTARAKEBUMENKEDIRIKEEROMKENDALKENDARIKEP. SIAU TAGULANDANG BIAROKEPAHIANGKEPULAUAN ANAMBASKEPULAUAN ARUKEPULAUAN MENTAWAIKEPULAUAN RIAUKEPULAUAN SANGIHEKEPULAUAN SELAYARKEPULAUAN SERIBUKEPULAUAN SULAKEPULAUAN TALAUDKEPULAUAN YAPENKERINCIKETAPANGKLATENKLUNGKUNGKOLAKAKOLAKA UTARAKONAWE SELATANKONAWE UTARAKOTA AMBONKOTA BALIKPAPANKOTA BANDA ACEHKOTA BANDUNGKOTA BANJARKOTA BANJAR BARUKOTA BANJARMASINKOTA BATAMKOTA BATUKOTA BAU-BAUKOTA BEKASIKOTA BIMAKOTA BINJAIKOTA BITUNGKOTA BLITARKOTA BOGORKOTA BONTANGKOTA BUKIT TINGGIKOTA CILEGONKOTA CIMAHIKOTA CIREBONKOTA DENPASARKOTA DEPOKKOTA DUMAIKOTA GORONTALOKOTA GUNUNGSITOLIKOTA JAMBIKOTA JAYAPURAKOTA KEDIRIKOTA KENDARIKOTA KUPANGKOTA LANGSAKOTA LHOKSEUMAWEKOTA LUBUK LINGGAUKOTA MADIUNKOTA MAGELANGKOTA MAKASSARKOTA MALANGKOTA MANADOKOTA MATARAMKOTA MEDANKOTA MOBAGOKOTA MOJOKERTOKOTA PADANGKOTA PADANG PANJANGKOTA PADANG SIDEMPUANKOTA PAGAR ALAMKOTA PALANGKARAYAKOTA PALEMBANGKOTA PALOPOKOTA PALUKOTA PANGKAL PINANGKOTA PARE-PAREKOTA PARIAMANKOTA PASURUANKOTA PAYAKUMBUHKOTA PEKALONGANKOTA PEKANBARUKOTA PEMATANG SIANTARKOTA PONTIANAKKOTA PRABUMULIHKOTA PROBOLINGGOKOTA PROBOLINGGOKOTA PURWOKERTOKOTA SABANGKOTA SALATIGAKOTA SAMARINDAKOTA SAWAH LUNTOKOTA SEMARANGKOTA SERANGKOTA SIBOLGAKOTA SINGKAWANGKOTA SOLOKKOTA SORONGKOTA SUKABUMIKOTA SUNGAI PENUHKOTA SURABAYAKOTA SURAKARTAKOTA TANGERANGKOTA TANGERANG SELATANKOTA TANGERANG SELATANKOTA TANJUNG BALAIKOTA TANJUNG PINANGKOTA TARAKANKOTA TASIKMALAYAKOTA TEBING TINGGIKOTA TEGALKOTA TERNATEKOTA TIDOREKOTA TOMOHONKOTA WARINGIN TIMURKOTA YOGYAKARTAKOTABARUKOTAWARINGIN BARATKUANTAN SINGINGIKUBU RAYAKUDUSKULONPROGOKUNINGANKUPANGKUTAI BARATKUTAI KERTANEGARAKUTAI TIMURLABUAN BATULABUAN BATU SELATANLABUAN BATU UTARALAHATLAMANDAULAMONGANLAMPUNG BARATLAMPUNG SELATANLAMPUNG TENGAHLAMPUNG TIMURLAMPUNG UTARALANDAKLANGKATLEBAKLEBONGLEMBATALIMA PULUH KOTOLINGGALOMBOK BARATLOMBOK TENGAHLOMBOK TIMURLOMBOK UTARALUMAJANGLUWULUWU TIMURLUWU UTARAMADIUNMAGELANGMAGETANMAJALENGKAMAJENEMALANGMALINAUMALUKU BARAT DAYAMALUKU TENGAHMALUKU TENGGARAMALUKU TENGGARA BARATMAMASAMAMBERAMO RAYAMAMUJUMAMUJU UTARAMANDAILING NATALMANGGARAIMANGGARAI BARATMANGGARAI TIMURMANGGARAI TIMURMANOKWARIMAPPIMAROSMELAWIMERANGINMERAUKEMESUJIMETROMIMIKAMINAHASAMINAHASA SELATANMINAHASA TENGGARAMINAHSA UTARAMOJOKERTOMOROWALIMUARA ENIMMUARO JAMBIMUKO-MUKOMUNAMURUNG RAYAMUSI BANYUASINMUSI RAWASNABIRENAGAN RAYANAGEKONATUNANGADANGANJUKNGAWINIASNIAS BARATNIAS SELATANNIAS UTARANUNUKANOGAN ILIROGAN KOMERING ILIROGAN KOMERING ULUOGAN KOMERING ULU SELATANOGAN KOMERING ULU TIMURPACITANPADANG LAWASPADANG LAWAS UTARAPADANG PARIAMANPAKPAK BHARATPAMEKASANPANDEGLANGPANGKAJENE DAN KEPULAUANPANGKAJENE KEPULAUANPANIAIPARIMOPASAMANPASAMAN BARATPASERPASURUANPATIPEGUNUNGAN BINTANGPEKALONGANPELALAWANPEMALANGPENAJAM PASER UTAMAPESAWARANPESISIR SELATANPIDIEPIDIE JAYAPINRANGPOHUWATOPOLEWALI MANDARPONOROGOPONTIANAKPOSOPRINGSEWUPROBOLINGGOPROBOLINGGOPULANG PISAUPULAU MERANTIPULAU MOROTAIPUNCAK JAYAPURBALINGGAPURWAKARTAPURWOKERTOPURWOREJORAJA AMPATREJANG LEBONGREMBANGROKAN HILIRROKAN HULUROTENDAOSABU RAIJUASAMBASSAMOSIRSAMPANGSANGGAUSARMISAROLANGUNSAWAHLUNTOH-SIJUNJUNGSEKADAUSELUMASEMARANGSERAM BAGIAN BARATSERAM BAGIAN TIMURSERANGSERDANG BEDAGAISERUYANSIAKSIDENRENG RAPANGSIDENRENG RAPPANGSIDOARJOSIGISIKASIMALUNGUNSIMEULUESINJAISINTANGSITAROSITUBONDOSLEMANSOLOKSOLOK SELATANSOPPENGSORONGSORONG SELATANSRAGENSUBANGSUBULUSSALAMSUKABUMISUKAMARASUKOHARJOSUMBA BARATSUMBA BARAT DAYASUMBA TENGAHSUMBA TIMURSUMBAWASUMBAWA BARATSUMEDANGSUMENEPSUPIORITABALONGTABANANTAKALARTAMBRAUWTANA TORAJATANAH BUMBUTANAH DATARTANAH LAUTTANAH TIDUNGTANGERANGTANGERANGTANGGAMUSTANJUNG JABUNG BARATTANJUNG JABUNG TIMURTAPANULI SELATANTAPANULI TENGAHTAPANULI UTARATAPINTASIKMALAYATEBOTEGALTELUK BINTUNITELUK WONDAMATEMANGGUNGTERNATETIMOR TENGAH SELATANTIMOR TENGAH UTARATOBA SAMOSIRTOJO UNA-UNATOLI-TOLITOLIKARATORAJA UTARATRENGGALEKTUBANTULANG BAWANGTULANG BAWANG BARATTULUNGAGUNGWAJOWAKATOBIWAROPENWAY KANANWONOGIRIWONOSOBOYAHUKIMO



District (Kecamatan)
CEMPAKA PUTIHGAMBIRJOHAR BARUKEMAYORANMENTENGSAWAH BESARSENENTANAH ABANG



Village/Sub-district (Kelurahan)
CIDENGDURI PULOGAMBIRKEBON KELAPAPETOJO SELATANPETOJO UTARA



RT/RW
 /



ZIP Code





        
            
                Phone and FaxPhone TypePhone No.Action



Add Phone
new ToolTip(&quot;frmMain:j_id97&quot;,&quot;frmMain:btnAddPhone_phone&quot;,{'showEvent':'mouseover'} );






            
    
        
            ReferenceSalutationReference NameTitleReference AddressMobile1Mobile2Phone NoExtEmailActionMR.MRS.MS.BRANCH MANAGERCOMMISIONERDIRECTOREXECUTIVE DIRECTORFINANCE MANAGERHUSBANDLESSEELESSEE'S COMPANYMANAGERMARKETING ADMINMARKETING MANAGEROTHEROWNERPESERO KOMANDITERPRESIDENT COMMISIONERPRESIDENT DIRECTORSONSTAFFVICE DIRECTORVICE PRESIDENTWIFEMR.MRS.MS.BRANCH MANAGERCOMMISIONERDIRECTOREXECUTIVE DIRECTORFINANCE MANAGERHUSBANDLESSEELESSEE'S COMPANYMANAGERMARKETING ADMINMARKETING MANAGEROTHEROWNERPESERO KOMANDITERPRESIDENT COMMISIONERPRESIDENT DIRECTORSONSTAFFVICE DIRECTORVICE PRESIDENTWIFE
            Add PIC
new ToolTip(&quot;frmMain:j_id146&quot;,&quot;frmMain:btnAddPIC&quot;,{'showEvent':'mouseover'} );

        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:contentWrapper&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Customer/Personal/Page_FormCDBPersonal/iframe_popupFrame</value>
   </webElementProperties>
</WebElementEntity>
