<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BRANCH MANAGERCOMMISION</name>
   <tag></tag>
   <elementGuidId>2c64e1fe-c562-4af2-ab84-278ed52733b9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:tblPIC:0:j_id114</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BRANCH MANAGERCOMMISIONERDIRECTOREXECUTIVE DIRECTORFINANCE MANAGERHUSBANDLESSEELESSEE'S COMPANYMANAGERMARKETING ADMINMARKETING MANAGEROTHEROWNERPESERO KOMANDITERPRESIDENT COMMISIONERPRESIDENT DIRECTORSONSTAFFVICE DIRECTORVICE PRESIDENTWIFE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:tblPIC:0:j_id112&quot;)/select[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Customer/Personal/Page_FormCDBPersonal/iframe_popupFrame</value>
   </webElementProperties>
</WebElementEntity>
