<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_201620172018</name>
   <tag></tag>
   <elementGuidId>80ddb046-8798-4962-a1f4-9e838110baa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:tblPeriodList:0:solbYear&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'frmMain:tblPeriodList:0:solbYear' and @name = 'frmMain:tblPeriodList:0:solbYear' and (text() = '201620172018' or . = '201620172018') and @ref_element = 'Object Repository/Customer/Personal/Page_FormCDBPersonal/iframe_popupFrame_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:tblPeriodList:0:solbYear</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:tblPeriodList:0:solbYear</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('frmMain',event,{'similarityGroupingId':'frmMain:tblPeriodList:0:j_id92','parameters':{'frmMain:tblPeriodList:0:j_id92':'frmMain:tblPeriodList:0:j_id92'} ,'containerId':'frmMain:j_id73'} )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>201620172018</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:tblPeriodList:0:solbYear&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Customer/Personal/Page_FormCDBPersonal/iframe_popupFrame_1</value>
   </webElementProperties>
</WebElementEntity>
