<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DownloadPO</name>
   <tag></tag>
   <elementGuidId>bd5ed00b-da3d-4a57-8944-0394f80d1da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:btnCommandLink_PrintPO&quot;]/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:btnCommandLink_PrintPO&quot;]/img</value>
   </webElementXpaths>
</WebElementEntity>
