<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FORD JAKARTA SELATANFOR</name>
   <tag></tag>
   <elementGuidId>458801a5-24f2-4721-b470-baf56e5e43dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmMain:supAssetList_supplierAsset&quot;)[count(. | //select[@id = 'frmMain:supAssetList_supplierAsset']) = count(//select[@id = 'frmMain:supAssetList_supplierAsset'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xhtml</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:supAssetList_supplierAsset</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:supAssetList_supplierAsset</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:showPickProgress('frmMain:supAssetFilter_supplierAsset', 'frmMain:imgProgressSupAsset_supplierAsset');A4J.AJAX.Submit('frmMain',event,{'control':this,'oncomplete':function(request,event,data){javascript:hideEl('frmMain:imgProgressSupAsset_supplierAsset')},'similarityGroupingId':'frmMain:j_id112','parameters':{'ajaxSingle':'frmMain:supAssetList_supplierAsset','frmMain:j_id112':'frmMain:j_id112'} ,'eventsQueue':'pickSupplierAsset','containerId':'frmMain:regAcct_supplierAsset'} )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FORD JAKARTA SELATANFORD JAKARTA TIMURHIBA UTAMA JAKARTAHONDA JAKARTA CENTERJAGUAR JAKARTA SELATANMAZDA JAKARTA BARATMAZDA JAKARTA SELATANMITSUBISHI BUMEN REDJA JAKARTAPORSCHE CENTER JAKARTA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:supAssetList_supplierAsset&quot;)</value>
   </webElementProperties>
</WebElementEntity>
