<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>last_page_of_table</name>
   <tag></tag>
   <elementGuidId>62a71c7f-13ae-42ab-94c9-7ba534d46254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:dtCifPersonal:j_id2831_table&quot;]/tbody/tr/td[16]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//td[(text() = '»»' or . = '»»')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> rich-datascr-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Event.fire(this, 'rich:datascroller:onscroll', {'page': 'last'});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>»»</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:dtCifPersonal:j_id2740_table&quot;)/tbody[1]/tr[1]/td[@class=&quot;rich-datascr-button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
