<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>open_task</name>
   <tag></tag>
   <elementGuidId>0a039972-9840-4690-a207-2ade888410fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div/div[4]/div/div[2]/span/table/tfoot/tr/td/div/table/tbody/tr/td[9]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmMain:CIFPersonalSearchResult_switch_off&quot;)[count(. | //div[@id = 'frmMain:CIFPersonalSearchResult_switch_off']) = count(//div[@id = 'frmMain:CIFPersonalSearchResult_switch_off'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-stglpnl-marker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:CIFPersonalSearchResult_switch_off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>»</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:CIFPersonalSearchResult_switch_off&quot;)</value>
   </webElementProperties>
</WebElementEntity>
