<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MR. ANDRI TRI WIBOWO SH - Copy</name>
   <tag></tag>
   <elementGuidId>8784c992-4cb2-4b4e-815b-1e6da7662651</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xhtml</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:customerList_defLessee</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:customerList_defLessee</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:showPickProgress('frmMain:acctFilter_defLessee', 'frmMain:imgProgressCustomer_defLessee');A4J.AJAX.Submit('frmMain',event,{'control':this,'oncomplete':function(request,event,data){javascript:hideEl('frmMain:imgProgressCustomer_defLessee');},'similarityGroupingId':'frmMain:j_id95','parameters':{'ajaxSingle':'frmMain:customerList_defLessee','frmMain:j_id95':'frmMain:j_id95'} ,'eventsQueue':'pickLessee','containerId':'frmMain:regAcct_defLessee'} )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MR. ANDRI TRI WIBOWO, SH.,M.HUM.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:customerList_defLessee&quot;)</value>
   </webElementProperties>
</WebElementEntity>
