<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_093017CV18002306</name>
   <tag></tag>
   <elementGuidId>dc83ec2d-a298-4af7-a562-47efc9b0a806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:list_pickFclt_default&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmMain:list_pickFclt_default&quot;)[count(. | //select[@id = 'frmMain:list_pickFclt_default' and @name = 'frmMain:list_pickFclt_default' and @ref_element = 'Object Repository/PaymentCashTransfer/Page_ MBF IT Core System - Payment/iframe_popupFrame']) = count(//select[@id = 'frmMain:list_pickFclt_default' and @name = 'frmMain:list_pickFclt_default' and @ref_element = 'Object Repository/PaymentCashTransfer/Page_ MBF IT Core System - Payment/iframe_popupFrame'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:list_pickFclt_default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:list_pickFclt_default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>callOverlay();javascript:showPickProgress('frmMain:filter_pickFclt_default', 'frmMain:imgProgressFclt_pickFclt_default');A4J.AJAX.Submit('frmMain',event,{'control':this,'oncomplete':function(request,event,data){javascript:hideEl('frmMain:imgProgressFclt_pickFclt_default');endOverlay()},'similarityGroupingId':'frmMain:j_id38','parameters':{'frmMain:j_id38':'frmMain:j_id38','ajaxSingle':'frmMain:list_pickFclt_default'} ,'eventsQueue':'pickFacility','containerId':'frmMain:reg_pickFclt_default'} )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	093017/CV18/002306
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:list_pickFclt_default&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PaymentCashTransfer/Page_ MBF IT Core System - Payment/iframe_popupFrame</value>
   </webElementProperties>
</WebElementEntity>
