<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_78910111213141516171819</name>
   <tag></tag>
   <elementGuidId>6e8e6e63-a8cc-4277-bab5-553cccee38d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmMain:dtListPayment_default:0:seqList&quot;)[count(. | //select[@id = 'frmMain:dtListPayment_default:0:seqList' and @ref_element = 'Object Repository/PaymentCashTransfer/Page_ MBF IT Core System - Payment/iframe_popupFrame']) = count(//select[@id = 'frmMain:dtListPayment_default:0:seqList' and @ref_element = 'Object Repository/PaymentCashTransfer/Page_ MBF IT Core System - Payment/iframe_popupFrame'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:dtListPayment_default:0:seqList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:dtListPayment_default:0:seqList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('frmMain',event,{'similarityGroupingId':'frmMain:dtListPayment_default:0:j_id172','parameters':{'frmMain:dtListPayment_default:0:j_id172':'frmMain:dtListPayment_default:0:j_id172'} } )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>789101112131415161718192021222324252627282930313233343536</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:dtListPayment_default:0:seqList&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PaymentCashTransfer/Page_ MBF IT Core System - Payment/iframe_popupFrame</value>
   </webElementProperties>
</WebElementEntity>
