<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TaskPanelBenchmarkPrice</name>
   <tag></tag>
   <elementGuidId>d7c37dce-cd49-4d32-8699-4a4633eebc8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:BenchmarkPriceSearchResult_header&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:BenchmarkPriceSearchResult_header&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
