<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RelationshiptoComplainant</name>
   <tag></tag>
   <elementGuidId>876f7d2f-818f-4663-bd7b-e4cb7629ff48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:f_RELATIONSHIP_COMPLAINANT&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:f_RELATIONSHIP_COMPLAINANT&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
