<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddAktePendirian</name>
   <tag></tag>
   <elementGuidId>aa5f1f39-37ba-4a34-9ac7-696aa4975a77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div/div/div[1]/span/span/fieldset/span/div/fieldset[3]/div[5]/a/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/form/div[2]/div/div/div[1]/span/span/fieldset/span/div/fieldset[3]/div[5]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
