<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Note</name>
   <tag></tag>
   <elementGuidId>3ccd3901-d7c4-48e3-9d73-f1eb93f8a859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;contentPage&quot;]/fieldset[3]/div[6]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;contentPage&quot;]/fieldset[3]/div[6]/textarea</value>
   </webElementXpaths>
</WebElementEntity>
