<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Facility - Asset - AddEdit</name>
   <tag></tag>
   <elementGuidId>c1f24633-b095-42ca-b565-d78672e36e44</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentWrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        
    Facility - Asset - Add/Edit
	
	
.panelColumns td {
	vertical-align: top;
}
//&lt;![CDATA[
		closeModal=function(){A4J.AJAX.Submit('frmMain',null,{'similarityGroupingId':'frmMain:j_id38','parameters':{'frmMain:j_id38':'frmMain:j_id38','ajaxSingle':'frmMain:j_id38'} ,'eventsQueue':'mQueueP'} )};
		//]]>WARNING







Richfaces.componentControl.attachAvailable('#frmMain\\:modalMessage_','onmaskclick','#frmMain\\:modalMessage_','hide')new ModalPanel('frmMain:modalMessage_',
				{
					width: 500,
					height: -1,

					minWidth: -1,
					minHeight: -1,

					resizeable: false,
					moveable: false,

					left: &quot;auto&quot;,
					top: &quot;auto&quot;,

					zindex: 1000,onresize: '',onmove: '',onshow: '',onhide: '',onbeforeshow: '',onbeforehide: '',
					domElementAttachment: &quot;&quot;,				
					keepVisualState: false,
					showWhenRendered: false,
					selectBehavior: &quot;disable&quot;,

					autosized: true,
					overlapEmbedObjects: false});

    

        if (document.title == &quot;&quot;) {
            document.title = &quot;:: MBF IT Core System 1.2.21 ::&quot;;
        } else {
            document.title = &quot;:: MBF IT Core System - Facility - Asset - Add/Edit 1.2.21 ::&quot;;
        }

    




                            
            					Asset



Number
 * Please save in order to generate







Type / Sub Type
VEHICLE

/
	Forklift
	Microminibus
	Minibus
	Others
	Pick Up
	Road Tractor
	Sedan
	SUV
	Truck








Manufacturer / Brand



	ACURA
	AIDA
	AJN
	ALFA ROMEO
	AMANDA
	ASTON MARTIN
	AUDI
	BENTLEY
	BISHAMON
	BMW
	BUICK
	CADILLAC
	CARENS
	CASSETTE
	CELETTE
	CHERRY
	CHERY
	CHEVROLET
	CHINFONG
	CHRYSLER
	CITROEN
	DAIHATSU
	DAIKIN
	DAIMLER
	DODGE
	ETNA
	ETNA
	FANTUZZI
	FERRARI
	FORD
	FOTON
	FUSHENG
	GEELY
	GUANG LI
	HESHBON
	HINO
	HONDA
	HUMMER
	HYUNDAI
	INFINITI
	ISUZU
	JAGUAR
	JASINDO
	JEEP
	JESINDO
	KIA
	KOMATSU
	KOMATSU
	LAMBORGHINI
	LAND ROVER
	LEXUS
	MASERATI
	MAZDA
	MEIJI
	MERCEDES BENZ
	MERCEDEZ
	MESIN
	MIKROTIK
	MINI
	MITSUBISHI
	MOLNAR
	MORRIS
	NASTOA
	NISSAN
	OPEL
	OTHERS
	PANASONIC
	PEUGEOT
	PORSCHE
	PROTON
	QUESTER
	RANGE ROVER
	ROLLS ROYCE
	SANY
	SHACMAN
	SMART
	SUBARU
	SUZUKI
	TAILIFT
	TOYOTA
	UD TRUCK
	VOLKSWAGEN
	VOLVO
	WASINO
	WRANGLER


/
//&lt;![CDATA[
		populateModelFunction=function(){A4J.AJAX.Submit('frmMain',null,{'similarityGroupingId':'frmMain:j_id70','parameters':{'frmMain:j_id70':'frmMain:j_id70','ajaxSingle':'frmMain:j_id70'} ,'eventsQueue':'populateUnitModel'} )};
		//]]>HONDA











Unit Model



ACCORD V6ACCORD VTI ATACCORD VTI MTACCORD VTI-L ATALL NEW CRV 1.5 CVTALL NEW CRV 1.5 PRESALL NEW CRV 1.5 TURBO CVTALL NEW CRV 1.5 TURBO PRESTIGEALL NEW CRV 2.0 CVTALL NEW JAZZ ALPHA MT 2014All New Jazz RS 1.5 CVTALL NEW JAZZ RS AT CVT 2014ALL NEW JAZZ RS CVT MMCALL NEW JAZZ RS MT 2014ALL NEW JAZZ S AT CVT 2014ALL NEW JAZZ S MT 2014BR-V E CVTBR-V E MTBR-V E PRESTIGE CVTBR-V S MTBrio 1.2 E Limited Edition ATBRIO CKD 1.2 E ATBRIO CKD 1.2 S ATBRIO E AUTOMATICBRIO E MANUALBRIO RSBRIO RS CVTBRIO RS CVT SEBRIO RS MTBRIO S AUTOMATICBRIO S MANUALBRIO SATYA A MTBRIO SATYA E CVTBRIO SATYA E MTBRIO SATYA S MTBRIO SPORT E ATBRIO SPORT E MTBRV 1.5 E CVTCITY E ATCITY E CVTCITY E MTCity ES ATCITY ES CVTCITY RS ATCITY RS MTCITY S ATCITY S CVTCITY S MTCIVIC 1.5 TC CVT PRESTIGECIVIC 1.5 TURBO CVTCIVIC 1.5 TURBO CVT PRESTIGECIVIC 1.5 TURBO E CVT HATCHBACKCIVIC 1.5L TURBOCIVIC 1.8 ATCIVIC 1.8 MTCIVIC 2.0 ATCIVIC HACTHBACKCIVIC HACTHBACK TURBOCIVIC HATCHBACKCIVIC HATCHBACK 1.5 TS S CVTCIVIC HATCHBACK E CVTCIVIC HATCHBACK S CVTCIVIC I-VTEC 1.8 ATCIVIC I-VTEC 1.8 MTCIVIC I-VTEC 2.0 MTCIVIC TC CVT ES 1.498 ccCIVIC TURBO 1.5 TC CVT ESCIVIC TYPE RCR-V 1.5L TURBOCR-V 1.5L TURBO PRESTIGECR-V 2.0 ATCR-V 2.0 L MTCR-V 2.0 MTCR-V 2.0LCR-V 2.4 ATCR-V 2.4 L PRES Special Edition ATCR-Z ATCR-Z CVTCR-Z MTCRV 1.5 L TURBOCRV 1.5 TURBO PRESTIGECRV 1.5L Turbo PrestigeCRV 2.0 ATCRV 2.0 L ATCRV 2.0 L MTCRV 2.0 MTCRV 2.0 PRESTIGE ATCRV 2.4 PRESTIGE ATCRV 2.4L CVTCRV 2.4L PRESTIGE CVTHONDA JAZZ RS MT MMC 2017HR-V 1.5 E Limited Edition CVTHR-V 1.5 E SPECIAL EDITIONHR-V 1.8 E Special Edition CVTHR-V 1.8 PRESTIGE CVT TWO TONEHR-V 1.8 PRESTIGE MUGENHRV 1.5 A MTHRV 1.5 E CVTHRV 1.5 E CVT MUGENHRV 1.5 S CVTHRV 1.5 S MTHRV 1.8 E CVTHRV 1.8 PRESTIGE CVTHRV 1.8 PRESTIGE MUGENHRV E CVT MMCJAZZ ALPHA MTJAZZ RS ATJAZZ RS CVTJAZZ RS CVT SPECIAL EDITIONJazz RS Limited Edition CVTJAZZ RS MTJAZZ RS MT MMC 2017JAZZ S ATJazz S CVTJAZZ S MTMobilio E CVTMobilio E CVT PRESTIGEMobilio E MTMobilio E Special Edition CVT PrestigeMobilio PRES Limited Edition CVTMobilio RS CVTMobilio RS Limited Edition CVTMobilio RS MTMobilio S MTNEW ACCORD 2.4 VTI-L ATNEW CITY E CVTNew CR-V 1.5L TurboNew CR-V 1.5L Turbo Prest.New HRV 1.5 E CVTODYSSEYODYSSEY AT











Manufacture Year
	2018
	2017
	2016
	2015
	2014
	2013
	2012
	2011
	2010
	2009
	2008
	2007
	2006
	2005
	2004
	2003
	2002
	2001
	2000
	1999
	1998
	1997
	1996
	1995
	1994
	1993
	1992
	1991
	1990
	1989
	1988
	1987
	1986
	1985
	1984
	1983
	1982
	1981
	1980
	1979
	1978
	1977
	1976
	1975
	1974
	1973
	1972
	1971
	1970
	1969
	1968
	1967
	1966
	1965
	1964
	1963
	1962
	1961
	1960
	1959
	1958
	1957
	1956
	1955
	1954
	1953
	1952
	1951
	1950
	1949
	1948
	1947
	1946
	1945
	1944
	1943
	1942
	1941
	1940
	1939
	1938
	1937
	1936
	1935
	1934
	1933
	1932
	1931
	1930
	1929
	1928
	1927
	1926
	1925
	1924
	1923
	1922
	1921
	1920
	1919








Description






                            


                Supplier Asset Information
Search(Use 3 or more character for filtering)
                
Name
HONDA AHMAD YANI
Branch
BANDUNG
Address
JL. A YANI NO. 352, BANDUNG 
Phone

022-7217271
Fax

022-7211713


        
            Insurance
Standard Rate 0 %
Year
Coverage Type
Premium Rate
Premium Before Discount
Discount
Premium After Discount
Year 1	ALL RISK (COMPREHENSIVE)
	ALL RISK - EARTH QUAKE
	ALL RISK - FLOOD
	ALL RISK - RSCC
	ALL RISK - RSCC+FLOOD
	ALL RISK - RSCC+FLOOD+EARTH QUAKE
	ALL RISK - RSCC+TEROR+E.QUAKE+FLOOD
	ALL RISK - RSCC+TERORISM+EARTHQUAKE
	ALL RISK - TERORISM+EARTH QUAKE
	ALL RISK - TERRORISM
	AllRisk+TPL10+PADV5+PAP4@5+RSCC+Fl+EQ+AW
	COMPREHENSIVE - FULL COVER
	LIFE INSURANCE COVERAGE
	PAD - Personal Accident Driver
	PAP - Personal Accident Passenger
	TLO - EARTH QUAKE
	TLO - FLOOD
	TLO - RSCC
	TLO - RSCC+FLOOD
	TLO - RSCC+TERORISM+EARTHQUAKE+FLOOD
	TLO - TERRORISM
	TOTAL LOSS ONLY (TLO)
	TPL - Third Party Liability
	TPP - Third Party Liability - Passenger
	TRANSIT EXTENSION CLAUSE
	WORKSHOP

 %

0.0000%

Year 2	ALL RISK (COMPREHENSIVE)
	ALL RISK - EARTH QUAKE
	ALL RISK - FLOOD
	ALL RISK - RSCC
	ALL RISK - RSCC+FLOOD
	ALL RISK - RSCC+FLOOD+EARTH QUAKE
	ALL RISK - RSCC+TEROR+E.QUAKE+FLOOD
	ALL RISK - RSCC+TERORISM+EARTHQUAKE
	ALL RISK - TERORISM+EARTH QUAKE
	ALL RISK - TERRORISM
	AllRisk+TPL10+PADV5+PAP4@5+RSCC+Fl+EQ+AW
	COMPREHENSIVE - FULL COVER
	LIFE INSURANCE COVERAGE
	PAD - Personal Accident Driver
	PAP - Personal Accident Passenger
	TLO - EARTH QUAKE
	TLO - FLOOD
	TLO - RSCC
	TLO - RSCC+FLOOD
	TLO - RSCC+TERORISM+EARTHQUAKE+FLOOD
	TLO - TERRORISM
	TOTAL LOSS ONLY (TLO)
	TPL - Third Party Liability
	TPP - Third Party Liability - Passenger
	TRANSIT EXTENSION CLAUSE
	WORKSHOP

 %

0.0000%

Year 3	ALL RISK (COMPREHENSIVE)
	ALL RISK - EARTH QUAKE
	ALL RISK - FLOOD
	ALL RISK - RSCC
	ALL RISK - RSCC+FLOOD
	ALL RISK - RSCC+FLOOD+EARTH QUAKE
	ALL RISK - RSCC+TEROR+E.QUAKE+FLOOD
	ALL RISK - RSCC+TERORISM+EARTHQUAKE
	ALL RISK - TERORISM+EARTH QUAKE
	ALL RISK - TERRORISM
	AllRisk+TPL10+PADV5+PAP4@5+RSCC+Fl+EQ+AW
	COMPREHENSIVE - FULL COVER
	LIFE INSURANCE COVERAGE
	PAD - Personal Accident Driver
	PAP - Personal Accident Passenger
	TLO - EARTH QUAKE
	TLO - FLOOD
	TLO - RSCC
	TLO - RSCC+FLOOD
	TLO - RSCC+TERORISM+EARTHQUAKE+FLOOD
	TLO - TERRORISM
	TOTAL LOSS ONLY (TLO)
	TPL - Third Party Liability
	TPP - Third Party Liability - Passenger
	TRANSIT EXTENSION CLAUSE
	WORKSHOP

 %

0.0000%

Extension Rate 0 %
Year
Coverage Type
Premium Rate
Premium
Remove
Third Party Liabilities 0 %
Year
Claim Limit
Rate
Amount
Remove
Year 1
 %
Remove
new ToolTip(&quot;frmMain:dtInsuranceTpl:0:j_id223&quot;,&quot;frmMain:dtInsuranceTpl:0:removeItem&quot;,{'showEvent':'mouseover'} );

Year 2
 %
Remove
new ToolTip(&quot;frmMain:dtInsuranceTpl:1:j_id223&quot;,&quot;frmMain:dtInsuranceTpl:1:removeItem&quot;,{'showEvent':'mouseover'} );

Year 3
 %
Remove
new ToolTip(&quot;frmMain:dtInsuranceTpl:2:j_id223&quot;,&quot;frmMain:dtInsuranceTpl:2:removeItem&quot;,{'showEvent':'mouseover'} );

TPL Passanger 0 %
Year
Claim Limit
Rate
Amount
Remove
Personal Accident (PA)
                
Driver 0 %
Year
PA Amount
Rate
Premium
Remove
Passenger 0 %
Year
PA Amount
Rate
No of Seat
Premium
Remove
Additional Insurance 0 %
Year
Premium
Remove



Insurance Premium








Total of Insurance Premium

0.00



Stamp Duty




Grand Total

0.00




        




                            
            					Other Information
* : Mandatory



Price
















Down Payment

14.29%







Color
	 
	BLACK
	BLUE
	BROWN
	CHAMPAGNE
	GOLD
	GREEN
	GREY
	NOT BLACK
	ORANGE
	OTHER COLOR
	PURPLE
	RED
	SILVER
	WHITE
	YELLOW








Note








Address BPKB*









City
	ACEH BARAT
	ACEH BARAT DAYA
	ACEH BESAR
	ACEH JAYA
	ACEH SELATAN
	ACEH SINGKIL
	ACEH TAMIANG
	ACEH TENGAH
	ACEH TENGGARA
	ACEH TIMUR
	ACEH UTARA
	AGAM
	ALOR
	ASAHAN
	ASMAT
	BADUNG
	BALANGAN
	BANDAR LAMPUNG
	BANDUNG
	BANDUNG BARAT
	BANGGAI
	BANGGAI KEPULAUAN
	BANGKA
	BANGKA BARAT
	BANGKA SELATAN
	BANGKA TENGAH
	BANGKALAN
	BANGLI
	BANJAR
	BANJARNEGARA
	BANTAENG
	BANTUL
	BANYUASIN
	BANYUMAS
	BANYUWANGI
	BARITO KUALA
	BARITO SELATAN
	BARITO TIMUR
	BARITO UTARA
	BARRU
	BARU
	BATANG
	BATANG HARI
	BATU BARA
	BEKASI
	BELITUNG
	BELITUNG TIMUR
	BELU
	BENER MERIAH
	BENGKALIS
	BENGKAYANG
	BENGKULU
	BENGKULU SELATAN
	BENGKULU TENGAH
	BENGKULU UTARA
	BERAU
	BIAK NUMFOR
	BIMA
	BIREUEN
	BLITAR
	BLORA
	BOALEMO
	BOGOR
	BOJONEGORO
	BOLAANG MONGONDO
	BOLAANG MONGONDO SELATAN
	BOLAANG MONGONDO TIMUR
	BOLMONG UTARA
	BOMBANA
	BONDOWOSO
	BONE
	BONE BOLANGO
	BOVEN DIGUL
	BOYOLALI
	BREBES
	BULELENG
	BULUKUMBA
	BULUNGAN
	BUNGO
	BUOL
	BURU
	BURU SELATAN
	BUTON
	BUTON UTARA
	CIAMIS
	CIANJUR
	CILACAP
	CIREBON
	DAIRI
	DEIYAI
	DELI SERDANG
	DEMAK
	DHARMASRAYA
	DOMPU
	DONGGALA
	EMPAT LAWANG
	ENDE
	ENREKANG
	FAKFAK
	FLORES TIMUR
	GARUT
	GAYO LUES
	GIANYAR
	GORONTALO
	GORONTALO UTARA
	GOWA
	GRESIK
	GROBOGAN
	GUNUNG KIDUL
	GUNUNG MAS
	HALMAHERA BARAT
	HALMAHERA SELATAN
	HALMAHERA TENGAH
	HALMAHERA TIMUR
	HALMAHERA UTARA
	HULU SUNGAI SELATAN
	HULU SUNGAI TENGAH
	HULU SUNGAI UTARA
	HUMBANG HASUNDUTAN
	INDRAGIRI HILIR
	INDRAGIRI HULU
	INDRAMAYU
	INTAN JAYA
	JAKARTA BARAT
	JAKARTA PUSAT
	JAKARTA SELATAN
	JAKARTA TIMUR
	JAKARTA UTARA
	JAYAPURA
	JAYAWIJAYA
	JEMBER
	JEMBRANA
	JENEPONTO
	JEPARA
	JOMBANG
	KAB. TUAL
	KABUPATEN DOGIYAI
	KABUPATEN DUGA
	KABUPATEN LANNY JAYA
	KABUPATEN MABERAMO TENGAH
	KABUPATEN PUNCAK
	KABUPATEN YALIMO
	KAIMANA
	KAMPAR
	KAPUAS
	KAPUAS HULU
	KARANG ASEM
	KARANGANYAR
	KARAWANG
	KARIMUN
	KARO
	KATINGAN
	KAUR
	KAYONG UTARA
	KEBUMEN
	KEDIRI
	KEEROM
	KENDAL
	KENDARI
	KEPAHIANG
	KEPULAUAN ANAMBAS
	KEPULAUAN ARU
	KEPULAUAN MENTAWAI
	KEPULAUAN RIAU
	KEPULAUAN SANGIHE
	KEPULAUAN SELAYAR
	KEPULAUAN SERIBU
	KEPULAUAN SULA
	KEPULAUAN TALAUD
	KEPULAUAN YAPEN
	KERINCI
	KETAPANG
	KLATEN
	KLUNGKUNG
	KOLAKA
	KOLAKA UTARA
	KONAWE SELATAN
	KONAWE UTARA
	KOTA AMBON
	KOTA BALIKPAPAN
	KOTA BANDA ACEH
	KOTA BANDUNG
	KOTA BANJAR
	KOTA BANJAR BARU
	KOTA BANJARMASIN
	KOTA BATAM
	KOTA BATU
	KOTA BAU-BAU
	KOTA BEKASI
	KOTA BIMA
	KOTA BINJAI
	KOTA BITUNG
	KOTA BLITAR
	KOTA BOGOR
	KOTA BONTANG
	KOTA BUKIT TINGGI
	KOTA CILEGON
	KOTA CIMAHI
	KOTA CIREBON
	KOTA DENPASAR
	KOTA DEPOK
	KOTA DUMAI
	KOTA GORONTALO
	KOTA GUNUNGSITOLI
	KOTA JAKARTA
	KOTA JAMBI
	KOTA JAYAPURA
	KOTA KEDIRI
	KOTA KENDARI
	KOTA KUPANG
	KOTA LANGSA
	KOTA LHOKSEUMAWE
	KOTA LUBUK LINGGAU
	KOTA MADIUN
	KOTA MAGELANG
	KOTA MAKASSAR
	KOTA MALANG
	KOTA MANADO
	KOTA MATARAM
	KOTA MEDAN
	KOTA MOBAGO
	KOTA MOJOKERTO
	KOTA PADANG
	KOTA PADANG PANJANG
	KOTA PADANG SIDEMPUAN
	KOTA PAGAR ALAM
	KOTA PALANGKARAYA
	KOTA PALEMBANG
	KOTA PALOPO
	KOTA PALU
	KOTA PANGKAL PINANG
	KOTA PARE-PARE
	KOTA PARIAMAN
	KOTA PASURUAN
	KOTA PAYAKUMBUH
	KOTA PEKALONGAN
	KOTA PEKANBARU
	KOTA PEMATANG SIANTAR
	KOTA PONTIANAK
	KOTA PRABUMULIH
	KOTA PROBOLINGGO
	KOTA SABANG
	KOTA SALATIGA
	KOTA SAMARINDA
	KOTA SAWAH LUNTO
	KOTA SEMARANG
	KOTA SERANG
	KOTA SIBOLGA
	KOTA SINGKAWANG
	KOTA SOLOK
	KOTA SORONG
	KOTA SUKABUMI
	KOTA SUNGAI PENUH
	KOTA SURABAYA
	KOTA SURAKARTA
	KOTA TANGERANG
	KOTA TANGERANG SELATAN
	KOTA TANJUNG BALAI
	KOTA TANJUNG PINANG
	KOTA TARAKAN
	KOTA TASIKMALAYA
	KOTA TEBING TINGGI
	KOTA TEGAL
	KOTA TERNATE
	KOTA TIDORE
	KOTA TOMOHON
	KOTA WARINGIN TIMUR
	KOTA YOGYAKARTA
	KOTAWARINGIN BARAT
	KUANTAN SINGINGI
	KUBU RAYA
	KUDUS
	KULONPROGO
	KUNINGAN
	KUPANG
	KUTAI BARAT
	KUTAI KERTANEGARA
	KUTAI TIMUR
	LABUAN BATU
	LABUAN BATU SELATAN
	LABUAN BATU UTARA
	LAHAT
	LAMANDAU
	LAMONGAN
	LAMPUNG BARAT
	LAMPUNG SELATAN
	LAMPUNG TENGAH
	LAMPUNG TIMUR
	LAMPUNG UTARA
	LANDAK
	LANGKAT
	LEBAK
	LEBONG
	LEMBATA
	LIMA PULUH KOTO
	LINGGA
	LOMBOK BARAT
	LOMBOK TENGAH 
	LOMBOK TIMUR
	LOMBOK UTARA
	LUMAJANG
	LUWU
	LUWU TIMUR
	LUWU UTARA
	MADIUN
	MAGELANG
	MAGETAN
	MAJALENGKA
	MAJENE
	MALANG
	MALINAU
	MALUKU BARAT DAYA
	MALUKU TENGAH
	MALUKU TENGGARA
	MALUKU TENGGARA BARAT
	MAMASA
	MAMBERAMO RAYA
	MAMUJU
	MAMUJU UTARA
	MANDAILING NATAL
	MANGGARAI
	MANGGARAI BARAT
	MANGGARAI TIMUR
	MANGGARAI TIMUR
	MANOKWARI
	MAPPI
	MAROS
	MELAWI
	MERANGIN
	MERAUKE
	MESUJI
	METRO
	MIMIKA
	MINAHASA
	MINAHASA SELATAN
	MINAHASA TENGGARA
	MINAHSA UTARA
	MOJOKERTO
	MOROWALI
	MUARA ENIM
	MUARO JAMBI
	MUKO-MUKO
	MUNA
	MURUNG RAYA
	MUSI BANYUASIN
	MUSI RAWAS
	NABIRE
	NAGAN RAYA
	NAGEKO
	NATUNA
	NGADA
	NGANJUK
	NGAWI
	NIAS
	NIAS BARAT
	NIAS SELATAN
	NIAS UTARA
	NUNUKAN
	OGAN ILIR
	OGAN KOMERING ILIR
	OGAN KOMERING ULU
	OGAN KOMERING ULU SELATAN
	OGAN KOMERING ULU TIMUR
	PACITAN
	PADANG LAWAS
	PADANG LAWAS UTARA
	PADANG PARIAMAN
	PAKPAK BHARAT
	PAMEKASAN
	PANDEGLANG
	PANGKAJENE KEPULAUAN
	PANIAI
	PARIMO
	PASAMAN
	PASAMAN BARAT
	PASER
	PASURUAN
	PATI
	PEGUNUNGAN BINTANG
	PEKALONGAN
	PELALAWAN
	PEMALANG
	PENAJAM PASER UTAMA
	PESAWARAN
	PESISIR SELATAN
	PIDIE
	PIDIE JAYA
	PINRANG
	POHUWATO
	POLEWALI MANDAR
	PONOROGO
	PONTIANAK
	POSO
	PRINGSEWU
	PROBOLINGGO
	PULANG PISAU
	PULAU MERANTI
	PULAU MOROTAI
	PUNCAK JAYA
	PURBALINGGA
	PURWAKARTA
	PURWOREJO
	RAJA AMPAT
	REJANG LEBONG
	REMBANG
	ROKAN HILIR
	ROKAN HULU
	ROTENDAO
	SABU RAIJUA
	SAMBAS
	SAMOSIR
	SAMPANG
	SANGGAU
	SARMI
	SAROLANGUN
	SAWAHLUNTOH-SIJUNJUNG
	SEKADAU
	SELUMA
	SEMARANG
	SERAM BAGIAN BARAT
	SERAM BAGIAN TIMUR
	SERANG
	SERDANG BEDAGAI
	SERUYAN
	SIAK
	SIDENRENG RAPANG
	SIDOARJO
	SIGI
	SIKA
	SIMALUNGUN
	SIMEULUE
	SINJAI
	SINTANG
	SITARO
	SITUBONDO
	SLEMAN
	SOLOK
	SOLOK SELATAN
	SOPPENG
	SORONG
	SORONG SELATAN
	SRAGEN
	SUBANG
	SUBULUSSALAM
	SUKABUMI
	SUKAMARA
	SUKOHARJO
	SUMBA BARAT
	SUMBA BARAT DAYA
	SUMBA TENGAH
	SUMBA TIMUR
	SUMBAWA
	SUMBAWA BARAT
	SUMEDANG
	SUMENEP
	SUPIORI
	TABALONG
	TABANAN
	TAKALAR
	TAMBRAUW
	TANA TORAJA
	TANAH BUMBU
	TANAH DATAR
	TANAH LAUT
	TANAH TIDUNG
	TANGERANG
	TANGGAMUS
	TANJUNG JABUNG BARAT
	TANJUNG JABUNG TIMUR
	TAPANULI SELATAN
	TAPANULI TENGAH
	TAPANULI UTARA
	TAPIN
	TASIKMALAYA
	TEBO
	TEGAL
	TELUK BINTUNI
	TELUK WONDAMA
	TEMANGGUNG
	TIMOR TENGAH SELATAN
	TIMOR TENGAH UTARA
	TOBA SAMOSIR
	TOJO UNA-UNA
	TOLI-TOLI
	TOLIKARA
	TORAJA UTARA
	TRENGGALEK
	TUBAN
	TULANG BAWANG
	TULANG BAWANG BARAT
	TULUNGAGUNG
	WAJO
	WAKATOBI
	WAROPEN
	WAY KANAN
	WONOGIRI
	WONOSOBO
	YAHUKIMO








Condition
	NEW
	REFINANCING
	USED





                            




Save
new ToolTip(&quot;frmMain:j_id414&quot;,&quot;frmMain:btnA_save&quot;,{'showEvent':'mouseover','horizontalOffset':30,'direction':'top\x2Dleft','followMouse':true} );
Saving and Copying
new ToolTip(&quot;frmMain:j_id418&quot;,&quot;frmMain:btnAL_wfCopy&quot;,{'showEvent':'mouseover','horizontalOffset':30,'direction':'top\x2Dleft','followMouse':true} );

                            Back
new ToolTip(&quot;frmMain:j_id425&quot;,&quot;frmMain:toRegister&quot;,{'showEvent':'mouseover','followMouse':true} );

                        
                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentWrapper&quot;)</value>
   </webElementProperties>
</WebElementEntity>
