<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ReqDisbursement03</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c66cd091-30dd-4ccd-97f7-d03c71945632</testSuiteGuid>
   <testCaseLink>
      <guid>38b01074-b67d-4b4d-8e29-e74f7d10f47c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RequestDisburse/MainTestCase/RequestDisburseAll</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ff5aaa80-2c58-42aa-b4ab-fdc2a4d68daa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/RequestDisburse/ConcurrentReqDisbursement/ConcurrentReqDisbursement3</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ff5aaa80-2c58-42aa-b4ab-fdc2a4d68daa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CustomerName</value>
         <variableId>19bae5fa-8dab-4fec-96a3-82e7ac591313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff5aaa80-2c58-42aa-b4ab-fdc2a4d68daa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BA</value>
         <variableId>c0e1d2e0-6d5b-4b7e-a42c-c193a6af141b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff5aaa80-2c58-42aa-b4ab-fdc2a4d68daa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BM</value>
         <variableId>4a28f238-7ca7-4cfc-9677-fb34a556fc4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff5aaa80-2c58-42aa-b4ab-fdc2a4d68daa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FINMaker</value>
         <variableId>1a70f987-0532-4e32-a69e-2753cfcb1010</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff5aaa80-2c58-42aa-b4ab-fdc2a4d68daa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FINChecker</value>
         <variableId>89f9f867-243a-42fa-be20-a0af2a95ed37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff5aaa80-2c58-42aa-b4ab-fdc2a4d68daa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FINDIR</value>
         <variableId>a9ac9890-882e-4688-a8e9-d32c9a19cf77</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
