<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CalculationMethod</name>
   <tag></tag>
   <elementGuidId>614d9275-a0f2-42fc-bc6c-d8ced9f306d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:pnlDetailMenu&quot;]/div[1]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'frmMain:j_id1279' and (text() = 'FIX INSTALLMENT FROM FLATFIXED INSTALLMENTFIXED PRINCIPALIRREGULAR PAYMENT' or . = 'FIX INSTALLMENT FROM FLATFIXED INSTALLMENTFIXED PRINCIPALIRREGULAR PAYMENT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:j_id1279</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>A4J.AJAX.Submit('frmMain',event,{'similarityGroupingId':'frmMain:j_id1281','parameters':{'frmMain:j_id1281':'frmMain:j_id1281'} } )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FIX INSTALLMENT FROM FLATFIXED INSTALLMENTFIXED PRINCIPALIRREGULAR PAYMENT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:pnlDetailMenu&quot;)/div[@class=&quot;fieldPackage&quot;]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
