<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NetDownAmount</name>
   <tag></tag>
   <elementGuidId>af4bd724-3403-4b42-9855-0c65361e2a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:pnlFee&quot;]/fieldset/table/tbody/tr/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:pnlFee&quot;]/fieldset/table/tbody/tr/td[2]/label</value>
   </webElementXpaths>
</WebElementEntity>
