<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HomeTaskFirstPage</name>
   <tag></tag>
   <elementGuidId>984eecfb-34e9-43fa-a50c-e595c2f18765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:dtFacility:j_id2934_table&quot;]/tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:dtFacility:j_id2934_table&quot;]/tbody/tr/td[1]</value>
   </webElementXpaths>
</WebElementEntity>
