<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoadingScreen</name>
   <tag></tag>
   <elementGuidId>135d58d0-1594-44ea-9dc2-7f901fc3e642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;modalPanelContentTable&quot;]/tbody/tr/td/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;modalPanelContentTable&quot;]/tbody/tr/td/label</value>
   </webElementXpaths>
</WebElementEntity>
