<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SendNextButton</name>
   <tag></tag>
   <elementGuidId>00f57a0e-16fc-4ca2-a776-ab63638b0c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:btnA_wfNextWithoutGoHomeExec&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:btnA_wfNextWithoutGoHomeExec&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
