<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddPhone</name>
   <tag></tag>
   <elementGuidId>5d276a4e-0eea-49e7-997d-ce80ce9dc4e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div/span[2]/fieldset/table[2]/tbody/tr/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CDB/Personal/ComboBoxInput/Address/IframeAddress</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/form/div/span[2]/fieldset/table[2]/tbody/tr/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
