<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddAktaPerubahan</name>
   <tag></tag>
   <elementGuidId>04d3c843-26ca-4043-a0c8-4f6c05ed8c52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div/div/div[1]/span/span/fieldset/span/div/fieldset[4]/div[5]/a/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/form/div[2]/div/div/div[1]/span/span/fieldset/span/div/fieldset[4]/div[5]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
