<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ABN Amro Bank NVAmerica</name>
   <tag></tag>
   <elementGuidId>a72b95e6-4324-4db2-894a-29e77c2bcf3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:dtIntroducer:1:bankName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:dtIntroducer:1:bankName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:dtIntroducer:1:bankName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABN Amro Bank NVAmerican Express Bank Ltd.ATEST BankBangkok Bank Ltd.Bank Agris/FinconesiaBank AgroniagaBank Agung AsiaBank AkenBank AlfaBank AlfindoBank AndaraBank AndromedaBank AngkasaBank Angkatan Perang/ASPACBank Anglomas InternasionalBank AnricoBank AntardaerahBank ANZ PaninBank Arta GrahaBank Arta Niaga KencanaBank Arta PrimaBank Arta PusaraBank Artha Graha InternasionalBank Artos IndonesiaBank Arya PanduartaBank AsiaticBank AstriaBank BajaBank Barclays IndonesiaBank BCA SyariahBank Bhumy BahariBank Bisnis InternasionalBank BNI SyariahBank BNP Paribas IndonesiaBank BRI SyariahBank Buana Tat LeeBank Budi InternasionalBank BukopinBank Bumi ArtaBank Bumi Arta IndonesiaBank Bumi DayaBank Bumiraya UtamaBank Capital IndonesiaBank Central AsiaBank Central DagangBank Centratama NasionalBank Centris InternasionalBank Chinatrust IndonesiaBank CIMB NiagaBank CiputraBank CitraBank CommonwealthBank ContinentalBank Dagang BaliBank Dagang dan IndustriBank Dagang Nasional IndonesiaBank Dagang NegaraBank Dai-chi Kangyo IndonesiaBank Dana Asia/NatinBank Dana HutamaBank Danamon IndonesiaBank DanpacBank DBS IndonesiaBank DekaBank Dewa RutjiBank Dharmala NugrahaBank Dipo InternationalBank DKI JakartaBank DummyBank DutaBank DwipaBank Ekonomi RaharjaBank Eksekutif InternasionalBank Ekspor Impor IndonesiaBank Fama InternasionalBank First Indonesia Fin.&amp;Inv. Corp.Bank GaneshaBank GlobalBank Gunung KencanaBank Gunung KentjanaBank HagakitaBank Hagaku/HagabankBank Halim IndonesiaBank HanaBank Hanil TamaraBank Harapan SantosaBank Harda InternasionalBank HarmoniBank HastinBank HokindoBank HS 1906Bank IBJ IndonesiaBank ICB BumiputeraBank ICBC IndonesiaBank Ina PerdanaBank Index SelindoBank Indo MonexBank IndonesiaBank Indonesia RayaBank IndotradeBank IndovestBank IntermodernBank Internasional Finance IndonesiaBank Internasional IndonesiaBank Jabar Banten SyariahBank Jabar Banten/BJBBank JakartaBank Jasa JakartaBank KesawanBank Kesejahteraan EkonomiBank KharismaBank KosaBank Kredit UniversalBank Lautan BerlianBank LCTB Central AsiaBank LimanBank MandiriBank Mashill UtamaBank MaspionBank MataramBank Mayapada InternationalBank Mayindo PertamaBank MayoraBank MediaBank MegaBank MestikaBank Metro Ekspres/IntanBank Metro ExpressBank MetropolitanBank MitraniagaBank Mitsui SwadharmaBank Mizuho IndonesiaBANK MNCBank MuamalatBank Multi Arta SentosaBank Namura InternusaBank NasionalBank NationalnobuBank Negara Indonesia 1946Bank Niaga SyariahBank NISPBank Nusa InternasionalBank Nusa NasionalBank Nusantara ParahyanganBank OCBC IndonesiaBank OCBC NISPBank of America NA &amp; SABank OrientBank PacificBank Pan IndonesiaBank Panin Syariah/Bersaudara Jaya-HarfaBank Papan SejahteraBank PatriotBank PDFCIBANK PEKREDITAN RAKYAT KSBank PelitaBank Pembangunan IndonesiaBank Pembangunan IndustriBank Perkembangan AsiaBank Perkembangan Surya KencanaBank Permata tbkBank Perniagaan UmumBank Persatuan Asia/SinobankBank PikkoBank PinaesaanBank PosBank Prima MasterBank Putra Surya PerkasaBank Rahardja MakmurBank Rakyat IndonesiaBank RamaBank Ratu/SinergyBank Resona PerdaniaBank Risjad Salim Intl.Bank Royal IndonesiaBank Sahabat Purba DanartaBank Sampoerna/Delta BankBank Sangga KencanaBank SanhoBank Sanwa/UFJ IndonesiaBank SBI IndonesiaBank SewuBank SGPBank ShintaBank Sinar Harapan BaliBank SinarmasBank SolidaBank South East AsiaBank Subentra InternasionalBank SukapuraBank Sumitomo Mitsui IndonesiaBank SupremeBank SuryaBank SwadesiBank Syariah BukopinBank Syariah MandiriBank Syariah Mega IndonesiaBank Tabungan NegaraBank Tabungan Pensiunan NasionalBank Tani Nas./Prima ExpressBank TataBank Tiara AsiaBank TMS/Kredit AsiaBank Tokai LippoBank Umum AsiaBank Umum Majapahit DjayaBank Umum NasionalBank Umum PembangunanBank Umum ServitiaBank United CityBank UniversalBank UOB BuanaBank UOB IndonesiaBank UppindoBank Victoria InternationalBank Victoria SyariahBank Windu KencanaBank Windu Kentjana InternationalBank Woori IndonesiaBANK WOORI SAUDARABank Yakin MakmurBank Yudha BhaktiBNI SYARIAHBPD AcehBPD BaliBPD BengkuluBPD JambiBPD Jawa TengahBPD Jawa TimurBPD Kalimantan BaratBPD Kalimantan SelatanBPD Kalimantan TengahBPD Kalimantan TimurBPD LampungBPD MalukuBPD Nusa Tenggara BaratBPD Nusa Tenggara TimurBPD PapuaBPD RiauBPD Sulawesi SelatanBPD Sulawesi TengahBPD Sulawesi TenggaraBPD Sulawesi UtaraBPD Sumatera BaratBPD Sumatera Selatan dan Bangka BelitungBPD Sumatera UtaraBPD YogyakartaBPR KSBTN SYARIAHCentury Intrvst Corp/MutiaraCitibankDeutsche Bank AG.Hana BankJ TRUST INDONESIAJP Morgan Chase BankKorea Exchange Bank IndonesiaLippobankMaybank IndocorpOverseas Express Bank/UtamaPetty CashPrasidha Bank UtamaPT BANK HSBC INDONESIARabobank InternasionalRabobank International IndonesiaSedjahtera Bank UmumSociete Generale IndonesiaStandard Chartered BankTamara Commercial BankThe Bank of ChinaThe Bank of Tokyo Mitsubishi-UFJ Ltd.The Hongkong &amp; Shanghai Banking Corp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:dtIntroducer:1:bankName&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='frmMain:dtIntroducer:1:bankName']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//td[@id='frmMain:dtIntroducer:1:column6']/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISBURSE'])[2]/following::select[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Introducer'])[1]/following::select[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[5]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Introducer'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//tr[2]/td[6]/select</value>
   </webElementXpaths>
</WebElementEntity>
