<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ProcurementConc004</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>758184f7-208f-4c31-9349-d76b17b9c4f3</testSuiteGuid>
   <testCaseLink>
      <guid>5cef14af-5274-4de5-b485-2b47f533353c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProcurementConcurrent/Procurement04/PurchaseRequisition/MainTestCase/PurchaseReqAll</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>10bd3a1b-9fb7-434f-b0c1-7710406e9cd6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Procurement/ConcurrentProcurement4</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>10bd3a1b-9fb7-434f-b0c1-7710406e9cd6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ReqMaker</value>
         <variableId>378b36cb-0b3f-4f21-a16c-5b36172f4a2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>10bd3a1b-9fb7-434f-b0c1-7710406e9cd6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ReqChecker</value>
         <variableId>e846bf64-9864-445d-b1b5-dc7e9a957c5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>10bd3a1b-9fb7-434f-b0c1-7710406e9cd6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ItemDescription</value>
         <variableId>bfbac227-5a0d-45e8-a43c-35b9fa9eadf4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>170f42ad-c614-4363-ab3d-6ea13e1292c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75bf030f-0ec2-403e-8582-bbc9a3df8f09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProcurementConcurrent/Procurement04/BenchmarkPrice/MainTestCase/BenchmarkPriceAll</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cbe0b494-a495-4562-b761-04ce5be3dc3e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Procurement/ConcurrentProcurement4</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cbe0b494-a495-4562-b761-04ce5be3dc3e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>GaMaker</value>
         <variableId>79adf242-d367-4a40-81f9-6b42c0855c82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cbe0b494-a495-4562-b761-04ce5be3dc3e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>GaChecker</value>
         <variableId>168c3e78-bf54-475a-a3e0-605db7034928</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f82b1b28-649d-4491-bd15-cf3fe653b2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94905427-4071-42e3-b922-4554c1de4451</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b27b5d2-25b0-4900-b899-b796e1ec6655</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProcurementConcurrent/Procurement04/PurchaseOrder/MainTestCase/PurchaseOrderAll</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d10cecb-73e8-437a-9beb-7740147c3a91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79e238f3-c3c4-4a23-9069-4c98073f04fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21e182f0-e3eb-4de8-9c86-74669d7f9eec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProcurementConcurrent/Procurement04/RegisterInvoice/MainTestCaseInvoice/InvoiceAll</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d23c1f94-59ec-45f5-965e-6cfca973e6a8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Procurement/ConcurrentProcurement4</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d23c1f94-59ec-45f5-965e-6cfca973e6a8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>GaMaker</value>
         <variableId>af1ccb3f-5b67-4d80-b0cb-5daecfe8affd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d23c1f94-59ec-45f5-965e-6cfca973e6a8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>GaChecker</value>
         <variableId>16192a36-e509-4508-91dc-b213a7607d43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>671c78a5-bec7-4073-936a-961587ecad61</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10de3524-aef2-4f20-bdbc-e0db1c493f62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Procurement/Prepayment/MainTestCasePrepayment/PrepaymentAll</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05a9869b-bcac-4914-8d65-20d52ccbfc38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b36bb5c-c0d3-44d2-957c-a081560741b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36bec7b3-571c-4115-8dba-45e482503926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbd8adcc-754e-4b45-9e85-bb104415e137</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b10fd175-f8e8-431c-a915-0dc5f3902e42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97531451-e49d-4a58-b772-0b11775bf4ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0cb23955-7fc2-477b-9093-ab2fcfaf0439</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProcurementConcurrent/Procurement04/Payment/MainTestCasePayment/ProcurementPaymentAll</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2419fed-35db-4f4a-a247-092048258e61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de18e9c3-8ee6-4e3d-80fc-87d743097948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38261366-3f3c-46e5-a9b2-eb89edae24bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ce2b2ef-a168-4b6b-86b7-f16c0a562ab4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f674acd5-744a-42df-8657-c12957a84a85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bc50ad7-1b31-4d59-af85-c5968af0ff2e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
