<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpenTaskPO</name>
   <tag></tag>
   <elementGuidId>85429153-df94-436a-b0a5-80beb95f1dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:PurchaseOrderSearchResult_switch_off&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:PurchaseOrderSearchResult_switch_off&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
