<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreditType</name>
   <tag></tag>
   <elementGuidId>2d16c67e-ad66-4b95-8276-e11a8e3e70c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:pnlFinancingScheme&quot;]/fieldset/div[1]/label[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:pnlFinancingScheme&quot;]/fieldset/div[1]/label[3]</value>
   </webElementXpaths>
</WebElementEntity>
