<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InsTypeLabelPAIAD</name>
   <tag></tag>
   <elementGuidId>bcd9b201-f6f2-4891-8472-77f3d0cce5a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:insuranceTypeWrapper&quot;]/div/table/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:insuranceTypeWrapper&quot;]/div/table/tbody/tr/td[3]/label</value>
   </webElementXpaths>
</WebElementEntity>
