<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InsTypeLabelYearly</name>
   <tag></tag>
   <elementGuidId>2fd66d18-4522-4a5a-8dad-8e612a84c4eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:insuranceTypeWrapper&quot;]/div/table/tbody/tr/td[4]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:insuranceTypeWrapper&quot;]/div/table/tbody/tr/td[4]/label</value>
   </webElementXpaths>
</WebElementEntity>
