<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InsTypeLabelNet</name>
   <tag></tag>
   <elementGuidId>b021bf5f-4d9e-401c-89d0-b35525e9b902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:insuranceTypeWrapper&quot;]/div/table/tbody/tr/td[1]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:insuranceTypeWrapper&quot;]/div/table/tbody/tr/td[1]/label</value>
   </webElementXpaths>
</WebElementEntity>
