<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InterestRateSubsidy</name>
   <tag></tag>
   <elementGuidId>e6f0e0ff-60c6-4079-b6e8-5dbaa712ec8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:rateSchemeWrapper&quot;]/div[3]/label[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:rateSchemeWrapper&quot;]/div[3]/label[3]</value>
   </webElementXpaths>
</WebElementEntity>
