<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LifeInsurancePaidtoAmount</name>
   <tag></tag>
   <elementGuidId>f78e2dfb-a8b1-47d1-b50d-d85006bfb9a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:dtLifeIns:0:j_id851&quot;]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:dtLifeIns:0:j_id851&quot;]/label</value>
   </webElementXpaths>
</WebElementEntity>
