<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LifeInsuranceBankAcctName</name>
   <tag></tag>
   <elementGuidId>9bc5fba1-4f74-4534-8a63-39ab1e9db667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:dtLifeIns:0:lifeinsbankAcctName&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:dtLifeIns:0:lifeinsbankAcctName&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
