<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LifeInsurance</name>
   <tag></tag>
   <elementGuidId>0754c90f-507e-4f0b-8d03-2c12212c08b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:pnlViewCreditProtection&quot;]/fieldset/table[2]/tbody/tr[3]/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:pnlViewCreditProtection&quot;]/fieldset/table[2]/tbody/tr[3]/td[2]/label</value>
   </webElementXpaths>
</WebElementEntity>
