<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LifeInsuranceCompanyBankAccount</name>
   <tag></tag>
   <elementGuidId>53cc49d9-2869-4370-bb40-abd62a742a1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:dtLifeIns:0:lifeinsbankAcctNo&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:dtLifeIns:0:lifeinsbankAcctNo&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
