<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PackageValue</name>
   <tag></tag>
   <elementGuidId>eee21a20-2967-4b39-978d-d2596545c905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:pnlFinancingType&quot;]/table/tbody/tr[1]/td[2]/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:pnlFinancingType&quot;]/table/tbody/tr[1]/td[2]/label</value>
   </webElementXpaths>
</WebElementEntity>
