<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PaymentIndicator</name>
   <tag></tag>
   <elementGuidId>8dab2bf8-71b0-4864-bbad-7fd64edbe597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:paymentSchemePnl&quot;]/fieldset[1]/div[5]/label[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:paymentSchemePnl&quot;]/fieldset[1]/div[5]/label[3]</value>
   </webElementXpaths>
</WebElementEntity>
