<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PaymentFreq</name>
   <tag></tag>
   <elementGuidId>a23130e2-2eb3-40e4-a3f9-b4be3878a719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:pnlFinancingType&quot;]/table/tbody/tr[15]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:pnlFinancingType&quot;]/table/tbody/tr[15]/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
