<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubsidyATPM</name>
   <tag></tag>
   <elementGuidId>fa4906a9-070f-42ed-a5a4-478f473e4c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:rateSchemeWrapper&quot;]/div[3]/label[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:rateSchemeWrapper&quot;]/div[3]/label[3]</value>
   </webElementXpaths>
</WebElementEntity>
