<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TermofLease</name>
   <tag></tag>
   <elementGuidId>6bbe8ef7-1ae8-4a02-a6d0-cdb4408e885c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:pnlFinancingType&quot;]/table/tbody/tr[14]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:pnlFinancingType&quot;]/table/tbody/tr[14]/td[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
