<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ScrollRefund</name>
   <tag></tag>
   <elementGuidId>240ab4ea-c2ef-4f23-a507-29c4f3b197d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'frmMain:pnlIntroducer' and (text() = 'Refund Refund Payment TypeReceiver TypeNameAddressPhoneBank NameBank BranchBank Acct NameBank Acct NoCommissionAmountAction' or . = 'Refund Refund Payment TypeReceiver TypeNameAddressPhoneBank NameBank BranchBank Acct NameBank Acct NoCommissionAmountAction')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:pnlIntroducer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refund Refund Payment TypeReceiver TypeNameAddressPhoneBank NameBank BranchBank Acct NameBank Acct NoCommissionAmountAction</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:pnlIntroducer&quot;)</value>
   </webElementProperties>
</WebElementEntity>
