<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DocIssueDate</name>
   <tag></tag>
   <elementGuidId>dab6d83e-8696-4a65-ae25-797e987a3b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:tlDocumentIssueDateInputDate&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CDB/Company/CompanyRegistrationInfo/CompanyRegistration/iframeCompanyRegistration</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:tlDocumentIssueDateInputDate&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
