<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_frmMainbtnLogin</name>
   <tag></tag>
   <elementGuidId>7cdc70e5-b1b9-4a33-9528-97a3f9e1b8f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmMain:btnLogin&quot;)[count(. | //input[@id = 'frmMain:btnLogin' and @name = 'frmMain:btnLogin' and @type = 'image']) = count(//input[@id = 'frmMain:btnLogin' and @name = 'frmMain:btnLogin' and @type = 'image'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:btnLogin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:btnLogin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:btnLogin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:startLogin();callOverlay();A4J.AJAX.Submit('frmMain',event,{'oncomplete':function(request,event,data){javascript:stopLogin();endOverlay()},'similarityGroupingId':'frmMain:btnLogin','parameters':{'frmMain:btnLogin':'frmMain:btnLogin'} ,'actionUrl':'/Fintegrity/login.xhtml;jsessionid=T8y9+SsP83VLEjtW4XgIC8aM'} );return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/btn-login.gif;jsessionid=T8y9+SsP83VLEjtW4XgIC8aM</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:btnLogin&quot;)</value>
   </webElementProperties>
</WebElementEntity>
