<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckItemGaChecker</name>
   <tag></tag>
   <elementGuidId>19ea9f22-c944-4f6f-9c5c-e6ddeca943f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[2]/div/div/span[3]/fieldset[2]/table[2]/tbody/tr[1]/td/table/tbody/tr[1]/td[3]/span/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>/html/body/form/div[2]/div/div/span[3]/fieldset[2]/table[2]/tbody/tr[1]/td/table/tbody/tr[1]/td[3]/span/input</value>
   </webElementXpaths>
</WebElementEntity>
