<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d8f4aa5e-66cb-4232-87fa-1ef92fcdb24b</testSuiteGuid>
   <testCaseLink>
      <guid>b0d24816-e951-404b-864f-7a90a7096ef6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginLogout/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3700b34f-6092-4d77-beab-2a85e2571d44</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginLogout/Data_LoginLogout3</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3700b34f-6092-4d77-beab-2a85e2571d44</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>96475920-cc02-499a-b81f-3ec279b30e1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>409b7e90-7b18-4dfd-9d2e-773142d98801</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
