<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_frmMainbtnA_wfCancelExec</name>
   <tag></tag>
   <elementGuidId>8c883f8a-b7a4-4da6-ac41-3ab73c56fab6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:btnA_wfCancelExec</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:btnA_wfCancelExec</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (confirm('Are you sure you want to Cancel?')) { doNothing();toggleModalPanel('btnA_wfCancel', 'Show');} else { return false; };A4J.AJAX.Submit('frmMain',event,{'oncomplete':function(request,event,data){javascript:toggleModalPanel('btnA_wfCancel', 'Hide');setErrorFocus('');doNothing();},'similarityGroupingId':'frmMain:btnA_wfCancelExec','parameters':{'frmMain:btnA_wfCancelExec':'frmMain:btnA_wfCancelExec'} ,'eventsQueue':'eventsQueue'} );return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Fintegrity/img/button_cancel.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:btnA_wfCancelExec&quot;)</value>
   </webElementProperties>
</WebElementEntity>
