<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_InsuranceCompany</name>
   <tag></tag>
   <elementGuidId>6da9b348-7af5-463b-8dc9-2260c8280fa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:insCompanySelect&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmMain:insCompanySelect&quot;)[count(. | //select[@id = 'frmMain:insCompanySelect' and @name = 'frmMain:insCompanySelect']) = count(//select[@id = 'frmMain:insCompanySelect' and @name = 'frmMain:insCompanySelect'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:insCompanySelect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:insCompanySelect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ASURANSI RAKSA PRATIKARA, PT - Package 2017BESS CENTRAL INSURANCE, PT - Package 2017ASURANSI HARTA AMAN PRATAMA Tbk, PT - Package 2017ASURANSI PAN PASIFIC, PT . ( Truck Teratama )ASURANSI PAN PACIFIC, PT (OJK APRIL 2017)ASURANSI RAKSA PRATIKARA, PT (OJK APRIL2017)ASURANSI HARTA AMAN PRATAMA TBK, PT OJK (APRIL 2017)SOMPO ARTARINDO (OJK APRIL 2017)ASURANSI ARTARINDO, PT (OJK APRIL 2017)BESS CENTRAL INSURANCE, PT (OJK APRIL 2017)ASURANSI PAN PACIFIC, PT - PACKAGE 2018ASURANSI ARTARINDO.PT ( FIRE AC IMORA)ASURANSI PAN PACIFIC. PT ( ASSET WIYAKA)ASURANSI HARTA AMAN PRATAMA (TEST DRIVE)ASURANSI PAN PACIFIC. PT ( Thas Power))ACA INSURANCE, PT (New OJK APRIL) 2017PT. ASURANSI RAKSA PRATIKARA - SPECIAL PACKAGE AUDI 2017ASURANSI RAKSA PRATIKARA, PT - PACKAGE 2018ASURANSI PAN PACIFIC. PT ( Honda Nusantara)BESS CENTRAL INSURANCE, PT - Package 2018ASURANSI HARTA AMAN PRATAMA Tbk, PT - Package 2017ASURANSI ARTARINDO SOMPO, PT - PACKAGE 2018ACA INSURANCE, PT (PACKAGE 2018)ASURANSI HARTA AMAN PRATAMA Tbk, PT - OJK 2018ASURANSI RAKSA PRATIKARA, PT - OJK 2018ASURANSI PAN PACIFIC, PT - OJK 2018ASURANSI ARTARINDO SOMPO, PT (OJK 2018)BESS CENTRAL INSURANCE, PT - OJK 2018ACA INSURANCE Tbk, PT - OJK 2018ASURANSI PAN PACIFIC, PT - Package 2017SOMPO ARTARINDO (OJK 2017)SOMPO ARTARINDO - Package 2017</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:insCompanySelect&quot;)</value>
   </webElementProperties>
</WebElementEntity>
