<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PurposeOfUse</name>
   <tag></tag>
   <elementGuidId>915ec43a-93f0-4cac-a9b1-2a4a2e99f125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:assetPurpose&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'frmMain:assetPurpose' and @name = 'frmMain:assetPurpose' and (text() = 'CORE FAMILY MEMBERSOPERATIONAL/ STAFF USEOTHERSSELF - USE' or . = 'CORE FAMILY MEMBERSOPERATIONAL/ STAFF USEOTHERSSELF - USE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:assetPurpose</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:assetPurpose</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CORE FAMILY MEMBERSOPERATIONAL/ STAFF USEOTHERSSELF - USE</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:assetPurpose&quot;)</value>
   </webElementProperties>
</WebElementEntity>
