<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MinimumAcctBalance</name>
   <tag></tag>
   <elementGuidId>791b8b21-de99-48f8-9e14-981a94529b52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:minAccBalance&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'frmMain:minAccBalance' and @name = 'frmMain:minAccBalance' and (text() = 'GREATER THAN 3 MONTHS INSTALLMENTLOWER THAN 3 MONTHS INSTALLMENT' or . = 'GREATER THAN 3 MONTHS INSTALLMENTLOWER THAN 3 MONTHS INSTALLMENT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:minAccBalance</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:minAccBalance</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GREATER THAN 3 MONTHS INSTALLMENTLOWER THAN 3 MONTHS INSTALLMENT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:minAccBalance&quot;)</value>
   </webElementProperties>
</WebElementEntity>
