<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CDBInfo</name>
   <tag></tag>
   <elementGuidId>47b58019-fbf3-4440-a19b-df051ca9deb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:customerList_defLessee&quot;]/option[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'frmMain:customerList_defLessee' and @name = 'frmMain:customerList_defLessee' and (text() = 'MR. ABD RAHMANMR. RAHMANMR. RAHMANMRS. TATI SRI RAHMATMR. WAHMADMRS. HJ RAHMAHMRS. NURAHMEINIMR. MEMET RAHMATMR. TAUFIQUR RAHMANMR. AHMAD NAJIBMR. YUDA SEPTIYANTO RAHMANDOMR. MAHMUDMR. H.MAHMUD TOHA SIREGAR AKMR. CECEP RAHMAT HIDAYATMR. KEVIN RAHMAT SURYA ATMAJAMR. MAHMUD KARYANA, ST,MR. AHMAD BAGAWIMR. ERLANDA BAYU RAHMADIMR. AHMAD RIZA FARISYMS. YUNITA RAHMANINGRUMMS. AYUDYA OKTA VIANA RAHMANMR. ANDI AHMADMRS. HJ.MAHMUDAH .AR.MR. AHMAD AHIYAR, S.PDMR. HIRJA AHMADIMR. A. RAHMAN RMRS. AMSIH BINTI AHMADMRS. NUZULIA RAHMA FIRANIMR. A. RAHMATMR. PANCA WANANDA NURAHMANMR. MAHMUDMR. AHMAD GAMAMR. RAHMAT SUMADISASTRAMR. ANDI RAHMATMR. DERRI HUTOMO RAHMADHIMRS. ARI RAHMAWATI, S.Kep.NsMRS. RAHMAYATIMR. RAHMADI, SE .MMMR. ARI RAHMAT SAPUTRAMRS. KURNIA RAHMAWATI INSANIMR. FAISHAL FAHMI WMR. SATI RAHMANMR. M. RAHMAT ZAINMR. RAHMAD DAIBMR. MAHMUD ARIFINMR. RAHMAT YADIH. ABDURAHMAN' or . = 'MR. ABD RAHMANMR. RAHMANMR. RAHMANMRS. TATI SRI RAHMATMR. WAHMADMRS. HJ RAHMAHMRS. NURAHMEINIMR. MEMET RAHMATMR. TAUFIQUR RAHMANMR. AHMAD NAJIBMR. YUDA SEPTIYANTO RAHMANDOMR. MAHMUDMR. H.MAHMUD TOHA SIREGAR AKMR. CECEP RAHMAT HIDAYATMR. KEVIN RAHMAT SURYA ATMAJAMR. MAHMUD KARYANA, ST,MR. AHMAD BAGAWIMR. ERLANDA BAYU RAHMADIMR. AHMAD RIZA FARISYMS. YUNITA RAHMANINGRUMMS. AYUDYA OKTA VIANA RAHMANMR. ANDI AHMADMRS. HJ.MAHMUDAH .AR.MR. AHMAD AHIYAR, S.PDMR. HIRJA AHMADIMR. A. RAHMAN RMRS. AMSIH BINTI AHMADMRS. NUZULIA RAHMA FIRANIMR. A. RAHMATMR. PANCA WANANDA NURAHMANMR. MAHMUDMR. AHMAD GAMAMR. RAHMAT SUMADISASTRAMR. ANDI RAHMATMR. DERRI HUTOMO RAHMADHIMRS. ARI RAHMAWATI, S.Kep.NsMRS. RAHMAYATIMR. RAHMADI, SE .MMMR. ARI RAHMAT SAPUTRAMRS. KURNIA RAHMAWATI INSANIMR. FAISHAL FAHMI WMR. SATI RAHMANMR. M. RAHMAT ZAINMR. RAHMAD DAIBMR. MAHMUD ARIFINMR. RAHMAT YADIH. ABDURAHMAN') and @ref_element = 'Object Repository/Facility/FacilityRegister/Guarantor/Page_ MBF IT Core System - Facility/iframe_popupFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xhtml</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:customerList_defLessee</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:customerList_defLessee</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:showPickProgress('frmMain:acctFilter_defLessee', 'frmMain:imgProgressCustomer_defLessee');A4J.AJAX.Submit('frmMain',event,{'control':this,'oncomplete':function(request,event,data){javascript:hideEl('frmMain:imgProgressCustomer_defLessee');},'similarityGroupingId':'frmMain:j_id34','parameters':{'frmMain:j_id34':'frmMain:j_id34','ajaxSingle':'frmMain:customerList_defLessee'} ,'eventsQueue':'pickLessee','containerId':'frmMain:regAcct_defLessee'} )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MR. ABD RAHMANMR. RAHMANMR. RAHMANMRS. TATI SRI RAHMATMR. WAHMADMRS. HJ RAHMAHMRS. NURAHMEINIMR. MEMET RAHMATMR. TAUFIQUR RAHMANMR. AHMAD NAJIBMR. YUDA SEPTIYANTO RAHMANDOMR. MAHMUDMR. H.MAHMUD TOHA SIREGAR AKMR. CECEP RAHMAT HIDAYATMR. KEVIN RAHMAT SURYA ATMAJAMR. MAHMUD KARYANA, ST,MR. AHMAD BAGAWIMR. ERLANDA BAYU RAHMADIMR. AHMAD RIZA FARISYMS. YUNITA RAHMANINGRUMMS. AYUDYA OKTA VIANA RAHMANMR. ANDI AHMADMRS. HJ.MAHMUDAH .AR.MR. AHMAD AHIYAR, S.PDMR. HIRJA AHMADIMR. A. RAHMAN RMRS. AMSIH BINTI AHMADMRS. NUZULIA RAHMA FIRANIMR. A. RAHMATMR. PANCA WANANDA NURAHMANMR. MAHMUDMR. AHMAD GAMAMR. RAHMAT SUMADISASTRAMR. ANDI RAHMATMR. DERRI HUTOMO RAHMADHIMRS. ARI RAHMAWATI, S.Kep.NsMRS. RAHMAYATIMR. RAHMADI, SE .MMMR. ARI RAHMAT SAPUTRAMRS. KURNIA RAHMAWATI INSANIMR. FAISHAL FAHMI WMR. SATI RAHMANMR. M. RAHMAT ZAINMR. RAHMAD DAIBMR. MAHMUD ARIFINMR. RAHMAT YADIH. ABDURAHMAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:customerList_defLessee&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Facility/FacilityRegister/Guarantor/Page_ MBF IT Core System - Facility/iframe_popupFrame</value>
   </webElementProperties>
</WebElementEntity>
