<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>generatedcashno</name>
   <tag></tag>
   <elementGuidId>06960671-8222-4870-ae6e-dc6cf5b0eaae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:mainPanel&quot;]/fieldset/div[1]/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:mainPanel&quot;]/fieldset/div[1]/div[1]/label[2]</value>
   </webElementXpaths>
</WebElementEntity>
