<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectObject</name>
   <tag></tag>
   <elementGuidId>d2c12f70-bf95-4fcd-99b7-357c78eb5104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'frmMain:list_defFctl' and @name = 'frmMain:list_defFctl' and (text() = '130629/CV19/005495' or . = '130629/CV19/005495') and @ref_element = 'Object Repository/RequestDisburse/ReqDisburseList/iframe_Close_popupFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:list_defFctl&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xhtml</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:list_defFctl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:list_defFctl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>callOverlay();javascript:showPickProgress('frmMain:filter_defFctl', 'frmMain:imgProgressFclt_defFctl');A4J.AJAX.Submit('frmMain',event,{'control':this,'oncomplete':function(request,event,data){javascript:hideEl('frmMain:imgProgressFclt_defFctl');endOverlay()},'similarityGroupingId':'frmMain:j_id28','parameters':{'frmMain:j_id28':'frmMain:j_id28','ajaxSingle':'frmMain:list_defFctl'} ,'eventsQueue':'pickFacility','containerId':'frmMain:reg_defFctl'} )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>130629/CV19/005495</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:list_defFctl&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RequestDisburse/ReqDisburseList/iframe_Close_popupFrame</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:list_defFctl&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
