<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Back1Page</name>
   <tag></tag>
   <elementGuidId>5aa38d94-e0cd-4821-bc13-f98af3e4a7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:dtCifPersonal:j_id2831_table&quot;]/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:dtCifPersonal:j_id2831_table&quot;]/tbody/tr/td[2]</value>
   </webElementXpaths>
</WebElementEntity>
