<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UpdateAdditionalInfo</name>
   <tag></tag>
   <elementGuidId>6ee86c67-01ec-483e-9943-8283c9afd425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:modalMessage_fcltUpdateAddInfoDiv&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:modalMessage_fcltUpdateAddInfoDiv&quot;]</value>
   </webElementXpaths>
</WebElementEntity>
