<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>terminationEffDate</name>
   <tag></tag>
   <elementGuidId>7d6d9d84-028b-4276-a2b5-d071b432cfcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;frmMain:effDateInputDate&quot;][count(. | //*[@class = 'rich-calendar-input ' and @id = 'frmMain:effDateInputDate']) = count(//*[@class = 'rich-calendar-input ' and @id = 'frmMain:effDateInputDate'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;frmMain:effDateInputDate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rich-calendar-input </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:effDateInputDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;frmMain:effDateInputDate&quot;]</value>
   </webElementProperties>
</WebElementEntity>
