<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Bank</name>
   <tag></tag>
   <elementGuidId>740d4fab-9fd1-406c-b19d-c9a59cfdb087</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmMain:entryTypeList_otherEntryType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmMain:entryTypeList_otherEntryType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>callOverlay();;A4J.AJAX.Submit('frmMain',event,{'control':this,'oncomplete':function(request,event,data){endOverlay()},'similarityGroupingId':'frmMain:j_id56','parameters':{'ajaxSingle':'frmMain:entryTypeList_otherEntryType','frmMain:j_id56':'frmMain:j_id56'} ,'containerId':'frmMain:regEntryType_otherEntryType'} )</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	101010-PJ7-D - PETTY CASH PJ7 - DISBURSE
	101010-PJ7-R - PETTY CASH PJ7 - RECEIVE
	101060-PJ7-D - CASH IN BANK MEGA PJ7 - DISBURSE
	101060-PJ7-R - CASH IN BANK MEGA PJ7 - RECEIVE
	101103-PJ7-D - CASH IN BANK BII PJ7 - DISBURSE
	101103-PJ7-R - Cash IN BANK BII PJ7 - RECEIVE
	101104-PJ7-R - CASH IN BANK UOB PJ7 - RECEIVE
	101601 - PJ7 - D - CASH IN BANK  BNI VIRTUAL ACCOUNT PJ7 - DISBURSE
	101601-PJ7-R - CASH IN BANK  BNI VIRTUAL ACCOUNT PJ7 - RECEIVE
	103110 - OPERATING LEASE ASSET - OPERATING LEASE ASSET HO - RECEIVE
	103110 - OPERATING LEASE ASSET - DISBURSE - OPERATING LEASE ASSET HO - DISBURSE
	104100-PJ7-R - ASSET - OTHER RECEIVABLE PJ7 - RECEIVE
	104100a-PJ7-R - ENDORSEMENT INSURANCE PJ7 - RECEIVE
	105010-PJ7-D - LOAN TO EMPLOYEES PJ7 - DISBURSE
	106010-PJ7-D - PREPAID OFFICE RENT AND MAINTENANCE PJ7 - DISBURSE
	106020-PJ7-D - PREPAID HEALT INSURANCE PJ7 - DISBURSE
	106025-PJ7-D - PREPAID RENT APARTEMENT PJ7 - DISBURSE
	106030-PJ7-D - PREPAID INSURANCE PJ7 - DISBURSE
	106035-PJ7-D - PREPAID TAX 23 PJ7 - DISBURSE
	106036-PJ7-D - PREPAID PPH 25 PJ7 - DISBURSE
	106037-PJ7-D - V.A.T PJ7 - DISBURSE
	106040-PJ7-D - ASSET - OTHER PREPAID EXPENSE PJ7 - DISBURSE
	107010-PJ7-D - LEASEHOLD IMPROVEMENT PJ7 - DISBURSE
	107010-PJ7-R - LEASEHOLD IMPROVEMENT PJ7 - RECEIVE
	107020-PJ7-D - OFFICE FURNITURE AND FIXTURE PJ7 - DISBURSE
	107030-PJ7-D - OFFICE EQUIPMENT PJ7 - DISBURSE
	107040-PJ7-D - COMPUTER EQUIPMENT PJ7 - DISBURSE
	107050-PJ7-D - ASSET - MOTOR VEHICLES PJ7 - DISBURSE
	108010-PJ7-D - SOFTWARE - INTANGIBLE ASSETS PJ7 - DISBURSE
	109010-PJ7-D - REFUNDABLE DEPOSITS PJ7 - DISBURSE
	109020 - REPOSSESSED ASSETS -PJ7-R - REPOSSESSED ASSETS  PJ7 - Receive
	109020 - REPOSSESSED ASSETS DISBURSE-PJ7-D - REPOSSESSED ASSETS DISBURSE PJ7 - Disburse
	109070-PJ7-D - CONSTRUCTION IN PROGRESS PJ7 - DISBURSE
	109080-PJ7-D - SUSPENSE ACCOUNT PJ7 - DISBURSE
	211010-PJ7-D - ACCOUNTS PAYABLE PJ7 - DISBURSE
	211030-PJ7-D - LIABILITY - INSURANCE PAYABLE PJ7 - DISBURSE
	211050-HO - CP INSURANCE PAYABLE-DISBURSE
	211090-PJ7-D - OTHERS PAYABLE PJ7 - DISBURSE
	212062-PJ7-R - SHORT TERM LOAN - BNI PJ7 - RECEIVE
	213070-PJ7-D - ACCRUED ASTEK PJ7 - DISBURSE
	213071-PJ7-D - ACCRUED EXP SAL.WAGES  &amp; EMP BENEFIT PJ7 - DISBURSE
	213080-PJ7-D - ACCRUED CONSULTANT FEE PJ7 - DISBURSE
	213090-PJ7-D - ACCRUED AUDIT FEE PJ7 - DISBURSE
	213200-PJ7-D - ACCRUED OTHER EXPENSE PJ7 - DISBURSE
	214010-PJ7-D - ACCRUED INCOME TAX - ART.21 PJ7 - DISBURSE
	214020-PJ7-D - ACCRUED INCOME TAX - ART.23 PJ7 - DISBURSE
	214021-PJ7-D - ACCRUED INCOME TAX - ART 25 PJ7 - DISBURSE
	214022-PJ7-D - ACCRUED INCOME TAX - ART.4 AYAT 2 PJ7 - DISBURSE
	214030-PJ7-D - ACCRUED INCOME TAX - ART.26 US$ PJ7 - DISBURSE
	214032-PJ7-D - ACCRUED INCOME TAX - ART 26 JPY PJ7 - DISBURSE
	214040-PJ7-D - ACCRUED INCOME TAX - ART 29 PJ7 - DISBURSE
	216010-PJ7-D - ADVANCES FROM LESSEE PJ7 - DISBURSE
	216030-PJ7-D - ADVANCES FROM CUSTOMERS PJ7 - DISBURSE
	216040-PJ7-D - LIABILITY - ADVANCES VIRTUAL ACCOUNT PJ7 - DISBURSE
	222012 - OTHER COMPREHENSIVE INCOME - IFRS
	301010-PJ7-R - LEASE INCOME EARNED PJ7 - RECEIVE
	301020-PJ7-R - LEASE INCOME EARNED US$ PJ7 - RECEIVE
	301030-PJ7-R - LEASE OPERATING INCOME PJ7 - RECEIVE
	301110-PJ7-R - CONSUMER FINANCE INCOME EARNED PJ7 - RECEIVE
	301120-PJ7-R - CONSUMER FINANCE INCOME EARNED BALLON PAYMENT PJ7 - RECEIVE
	302010-PJ7-R - INTEREST INCOME ON CA PJ7 - RECEIVE
	302011-PJ7-R - INTEREST INCOME ON CA - MIZUHO PJ7 - RECEIVE
	302012-PJ7-R - INTEREST INCOME ON CA - MIZUHO US$ PJ7 - RECEIVE
	302030-PJ7-R - INTEREST INCOME ON TD - ONSHORE PJ7 - RECEIVE
	302031-PJ7-R - INTEREST INCOME ON TD MIZUHO - ONSHORE PJ7 - RECEIVE
	302040-PJ7-R - INTEREST INCOME ON TD - ONSHORE US$ PJ7 - RECEIVE
	302060-PJ7-R - INTEREST INCOME ON NOTES RECEIVABLE PJ7 - RECEIVE
	302072-PJ7-R - INTEREST INCOME ON SAVING - RP PJ7 - RECEIVE
	302073-PJ7-R - INTEREST INCOME ON LOAN EMPLOYEE PJ7 - RECEIVE
	303010-PJ7-R - COMMITMENT FEE INCOME - LEASING PJ7 - RECEIVE
	303011-PJ7-R - COMMITMENT FEE INCOME - LEASING US$ PJ7 - RECEIVE
	303012-PJ7-R - COMMITMENT FEE INCOME - CONSUMER FINANCE PJ7 - RECEIVE
	303020-PJ7-R - INSURANCE COMMISSIONS - LEASING PJ7 - RECEIVE
	303021-PJ7-R - INSURANCE COMMISSIONS - CONSUMER FINANCE PJ7 - RECEIVE
	303030-PJ7-R - PENALTY INTEREST INCOME PJ7 - RECEIVE
	303031-PJ7-R - PENALTY INTEREST INCOME US$ PJ7 - RECEIVE
	303050-PJ7-R - REV ALLOWANCE FOR D/B ACCOUNT - C/F PJ7 - RECEIVE
	304010-PJ7-R - GAIN ON EARLY TERMINATION OF LEASE CONTR PJ7 - RECEIVE
	304020-PJ7-R - GAIN ON EARLY TERM. OF CONSUMER FIN.CONT PJ7 - RECEIVE
	305010-PJ7-R - BAD DEBT RECOVERY PJ7 - RECEIVE
	306100-PJ7-R - GAIN OR LOSS ON FOREIGN EXCHANGE - TRANSACTION PJ7 - RECEIVE
	306110-PJ7-R - GAIN OR LOSS ON FOREIGN EXCHANGE - TRANSACTION PJ7 - RECEIVE
	306120-PJ7-R - GAIN OR LOSS ON FOREIGN EXCHANGE - TRANSACTION PJ7 - RECEIVE
	306200-PJ7-R - GAIN OR LOSS ON FOREIGN EXCHANGE - POSITION PJ7 - RECEIVE
	306210-PJ7-R - GAIN OR LOSS ON FOREIGN EXCHANGE - POSITION PJ7 - RECEIVE
	306220-PJ7-R - GAIN OR LOSS ON FOREIGN EXCHANGE - POSITION PJ7 - RECEIVE
	306300-PJ7-D - GAIN OR LOSS ON FOREIGN EXCHANGE PJ7 - DISBURSE
	306300-PJ7-R - GAIN OR LOSS ON FOREIGN EXCHANGE - MANUAL ENTRY PJ7 - RECEIVE
	307010-PJ7-R - GAIN OR LOSS ON SALE OF FIXED ASSETS PJ7 - RECEIVE
	308110-PJ7-R - GAIN OR LOSS ON SALE OF REPOSSES ASSETS            PJ7 - RECEIVE
	308120-PJ7-R - GAIN OR LOSS ON SALE OF REPOSSES ASSETS US$ PJ7 - RECEIVE
	309010-PJ7-R - REFUND TO DEALER PJ7 - RECEIVE
	309020-PJ7-R - INCOME FROM RENT OFFICE PJ7 - RECEIVE
	309050-PJ7-R - SUBSIDY RATE PJ7 - RECEIVE
	309090-PJ7-D - OTHERS PJ7 - DISBURSE
	309090-PJ7-R - OTHERS PJ7 - RECEIVE
	401010-PJ7-D - INTEREST EXPENSES - ONSHORE PJ7 - DISBURSE
	401030-PJ7-D - INTEREST EXPENSES - ONSHORE US$ PJ7 - DISBURSE
	401031-PJ7-D - INTEREST EXPENSES - ONSHORE JPY PJ7 - DISBURSE
	401032-PJ7-D - INTEREST EXPENSES - BANK MIZUHO INDONESIA IDR PJ7 - DISBURSE
	401040-PJ7-D - INTEREST EXPENSES - FACTORING US$ PJ7 - DISBURSE
	401050-PJ7-D - INTEREST EXPENSES- TRANSC.SWAP PJ7 - DISBURSE
	402010-PJ7-D - SWAP COST PJ7 - DISBURSE
	403005-PJ7-D - DEPR. EXP. - LEASEHOLD IMPROVEMENT PJ7 - DISBURSE
	403010-PJ7-D - DEPR. EXP. - OFFICE FURNITURE &amp; FIXTURE PJ7 - DISBURSE
	403020-PJ7-D - DEPR. EXP. - OFFICE EQUIPMENT PJ7 - DISBURSE
	403030-PJ7-D - DEPR. EXP. - COMPUTER EQUIPMENT PJ7 - DISBURSE
	403040-PJ7-D - DEPR. EXP. - VEHICLE PJ7 - DISBURSE
	403050-PJ7-D - AMORTIZATION EXPENCE-INTANGIBLE ASSETS PJ7 - DISBURSE
	403060-PJ7-D - DEPRECIATION EXPENSES- OPERATING LEASE ASSETS PJ7 - DISBURSE
	404010-PJ7-D - PROVISION FOR DOUBTFUL ACCOUNT PJ7 - DISBURSE
	404020-PJ7-D - PROVISION FOR DOUBTFUL ACCOUNT US$ PJ7 - DISBURSE
	404030-PJ7-D - BAD DEBT EXPENSE PJ7 - DISBURSE
	404040-PJ7-D - BAD DEBT EXPENSE US$ PJ7 - DISBURSE
	405001-PJ7-D - SALARIES AND WAGES PJ7 - DISBURSE
	405002-PJ7-D - ASTEK PJ7 - DISBURSE
	405003-PJ7-D - SAL, WAGES EMPLOYEE BENEFIT UU NO.13 PJ7 - DISBURSE
	405004-PJ7-D - OTHER EMPLOYEES ' BENEFITS PJ7 - DISBURSE
	405005-PJ7-D - TRAINING EXPENSES PJ7 - DISBURSE
	405006-PJ7-D - TRAVEL ACCOMODATION PJ7 - DISBURSE
	405007-PJ7-D - TRANSPORTATION EXPENSES PJ7 - DISBURSE
	405008-PJ7-D - ENTERTAINMENT PJ7 - DISBURSE
	405009-PJ7-D - REPRESENTATION PJ7 - DISBURSE
	405010-PJ7-D - ADVERTISING AND PROMOTION PJ7 - DISBURSE
	405011-LPG-D - MEMBERSHIP, PERIODICALS AND SUBSCRIPTION LPG -D
	405011-PJ7-D - MEMBERSHIP,PERIODICALS AND SUBSCRIPTION PJ7 - DISBURSE
	405012-BDG-D - OPERATING LEASE EXPENSE BDG - DISBURSE
	405012-CKG-D - OPERATING LEASE EXPENSE CKG - DISBURSE
	405012-FTW-D - OPERATING LEASE EXPENSE FTW - DISBURSE
	405012-LPG-D - OPERATING LEASE EXPENSE LPG - DISBURSE
	405012-MKS-D - OPERATING LEASE EXPENSE MKS - DISBURSE
	405012-PJ6-D - OPERATING LEASE EXPENSE PJ6 - DISBURSE
	405012-PJ7-D - OPERATING LEASE EXPENSE PJ7 - DISBURSE
	405012-SBY-D - OPERATING LEASE EXPENSE SBY - DISBURSE
	405012-SMG-D - OPERATING LEASE EXPENSE SMG - DISBURSE
	405012-TNG-D - OPERATING LEASE EXPENSE TNG - DISBURSE
	405013-PJ7-D - M/V - GAS, OIL AND PARKING PJ7 - DISBURSE
	405013-PJ7-R - M/V - GAS, OIL AND PARKING PJ7 - RECEIVE
	405014-PJ7-D - M/V - REPAIRS AND MAINTENANCE PJ7 - DISBURSE
	405014-PJ7-R - M/V - REPAIRS AND MAINTENANCE PJ7 - RECEIVE
	405015-PJ7-D - OFFICE RENT AND MAINTENANCE PJ7 - DISBURSE
	405015-PJ7-R - OFFICE RENT AND MAINTENANCE PJ7 - RECEIVE
	405016-PJ7-D - EQUIPMENT RENT AND MAINTENANCE PJ7 - DISBURSE
	405016-PJ7-R - EQUIPMENT RENT AND MAINTENANCE PJ7 - RECEIVE
	405017-PJ7-D - TELEX, TELEPHONE AND POSTAGE PJ7 - DISBURSE
	405018-PJ7-D - OFFICE SUPPLIES AND STATIONERIES PJ7 - DISBURSE
	405019-PJ7-D - INSURANCE EXPENSES PJ7 - DISBURSE
	405020-PJ7-D - OTHER OFFICE EXPENSES PJ7 - DISBURSE
	405021-PJ7-D - PRINTING EXPENSES PJ7 - DISBURSE
	405022-PJ7-D - FOTOCOPY EXPENSES PJ7 - DISBURSE
	405023-PJ7-D - INTERNET EXPENSES PJ7 - DISBURSE
	405024-PJ7-D - ELECTRICITY EXPENSES PJ7 - DISBURSE
	405025-PJ7-D - APARTEMENT EXPENSES PJ7 - DISBURSE
	405026-PJ7-D - SECURITY EXPENSES PJ7 - DISBURSE
	405027-PJ7-D - LEASE RENT PJ7 - DISBURSE
	405027-PJ7-R - LEASE RENT PJ7 - RECEIVE
	405028-PJ7-D - AUDIT FEE PJ7 - DISBURSE
	405029-PJ7-D - LEGAL FEE PJ7 - DISBURSE
	405030-PJ7-D - OTHER PROFESSIONAL FEE PJ7 - DISBURSE
	405031-PJ7-D - BANK PROVISION PJ7 - DISBURSE
	405032-PJ7-D - BANK CHARGES - MIZUHO PJ7 - DISBURSE
	405033-PJ7-D - BANK CHARGES PJ7 - DISBURSE
	405034-PJ7-D - GUARANTEE FEE PJ7 - DISBURSE
	405035-PJ7-D - STAMP DUTIES PJ7 - DISBURSE
	405036-PJ7-D - EDP EXPENSES PJ7 - DISBURSE
	405036-PJ7-R - EDP EXPENSES PJ7 - RECEIVE
	405037-PJ7-D - PROBLEM LOAN EXPENSES PJ7 - DISBURSE
	405038-PJ7-D - ADMIN BRANCH PJ7 - DISBURSE
	405039-PJ7-D - REFERENCE FEE PJ7 - DISBURSE
	405040-PJ7-D - COMISSION FEE PJ7 - DISBURSE
	405041-PJ7-D - OTHER GENERAL EXPENSES PJ7 - DISBURSE
	405042-PJ7-D - RECRUITMENT EXPENSES PJ7 - Disburse
	405042-PJ7-R - RECRUITMENT EXPENSES PJ7 - Receive
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmMain:entryTypeList_otherEntryType&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Internal Payment - Cash Transaction/Test 3/iframe_Close_popupFrame (1)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='frmMain:entryTypeList_otherEntryType']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmMain:otherEntryType']/tbody/tr/td[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entry Type'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected Entry Type:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETTY CASH PJ7 - DISBURSE'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
